Feat/yield
ubiquity/ubiquity-dollar pull request #251
Opened 2022-09-07 10:25 UTC by zgorizzo69

run:

```
mkdir lib run:

```
mkdir lib 
```
we should have a `ubiquity/ubiquity-dollar/contracts/yield-aggregator/lib` folder
```
forge install foundry-rs/forge-stdfor
```
```
forge install openzeppelin/openzeppelin-contracts
```
```
forge build
```
```
we should have a `ubiquity/ubiquity-dollar/contracts/yield-aggregator/lib` folder
```
forge install foundry-rs/forge-stdfor
```
```
forge install openzeppelin/openzeppelin-contracts
```
```
forge build
```

2022-09-07 10:52 UTC, pavlovcik commented
@0xcodercrane I hope you two can coordinate on merging the Foundry work. Not sure how you want to handle this but I'll let you take the lead as I have never used Foundry!

@zgorizzo69 if this is still in progress I suggest that you convert this to a draft pull request.

2022-09-07 10:52 UTC, pavlovcik approved these changes, later dismissed

2022-09-08 09:16 UTC, cuddle-dev requested changes

2022-09-08 09:16 UTC, 0xcodercrane commented on contracts/yield-aggregator/contracts/ProxyYieldAggregator.sol
> +import "forge-std/Test.sol";
we don't need Test.sol in production.

2022-09-08 09:16 UTC, cuddle-dev commented on contracts/yield-aggregator/README.md
> +forge test --mc Proxy  --fork-url https://eth-mainnet.alchemyapi.io/v2/YOURKEYHERE -vvvv
I think we should be able to run all the contracts tests in one script here

2022-09-08 09:16 UTC, cuddle-dev commented on contracts/yield-aggregator/test/utils/mocks/MockERC20.sol
> +}
MockFiles looks good to me.

2022-09-19 16:49 UTC, closed without merging