Feat/pre commit linting hook
ubiquity/ubiquity-dollar pull request #3
Opened 2021-08-11 01:57 UTC by Zequez

Added pre-commit linting hook; should run Eslint on all staged files before committing which should also fix and format with Prettier.

- `husky` to `package.json`
- `lint-staged` to `frontend/package.json`

It also [makes TypeScript checks with the use of eslint-plugin-tsc as demonstrated on this issue.](https://github.com/okonet/lint-staged/issues/468)

Everyone should run `yarn install` on the root so the Husky hooks get installed too. Maybe announce it on the #dev channel.

2021-08-11 02:19 UTC, pavlovcik requested changes

2021-08-11 02:19 UTC, pavlovcik commented on frontend/.eslintrc.js
>  };
I prefer to make these into JSONs!

2021-08-11 02:19 UTC, pavlovcik commented on frontend/components/context/connected.tsx
> +  const value: IConnectedContext = {
I don't believe in the `I` prefix for interfaces, would be great to change these to `ConnectedContext`

2021-08-11 02:19 UTC, pavlovcik commented on frontend/next.config.js
> +    config.plugins.push(new WindiCSS());
You know my thoughts on this WindiCSS thing...

2021-08-11 02:19 UTC, pavlovcik commented on frontend/pages/_app.tsx
> +import "windi.css";
🤨 ser pls

2021-08-11 02:19 UTC, pavlovcik commented on frontend/tsconfig.json
> +    "windi-attributify.d.ts",
ser pls

2021-08-11 02:19 UTC, pavlovcik commented on frontend/windi.config.ts
> +});
pls

2021-08-18 00:42 UTC, Zequez commented
@pavlovcik are you wanting me to remove WindiCSS? Because I would rather it be kept 😆

2021-08-18 00:48 UTC, pavlovcik commented
Yea @zgorizzo69 and I think it's irresponsible to introduce new technologies unless most of the industry is already using it.

2021-08-18 01:46 UTC, Zequez commented
I mean, it's just CSS, is not like we're introducing groundbreaking tech; it's a CSS dev tool for our own dashboard. It's like using SASS, LESS, Webpack, (...or Bootstrap); it's not an architectural change or even a coding change; it's a tool to make CSS more maintainable long term; a set of CSS utilities that are modular, configurable and easy to use. [Did you explore the Tailwind website](https://tailwindcss.com/)? And [the article from the original author about the reasoning behind it](https://adamwathan.me/css-utility-classes-and-separation-of-concerns/)?

2021-09-02 23:03 UTC, Zequez commented
There I added Tailwind in a way that we commit the style output to the repo; is that what you had in mind @pavlovcik ? I also changed WindiCSS with Tailwind just because Tailwind is more popular and known so people don't get confused.

2021-09-02 23:05 UTC, Zequez commented
If this gets merged, then we can just close #2  because this branch includes that one; and if I merge back the last change to that branch then they are essentially the same branch. How the heck do people manage to make multiple PRs that change the same files without these being co-dependant? 😆

2021-09-02 23:27 UTC, pavlovcik commented
> There I added Tailwind in a way that we commit the style output to the repo; is that what you had in mind @pavlovcik ?
Yeah as long as it doesn't become a requirement for future developers to be productive then I think its fine. @zgorizzo69 any thoughts?

2021-09-05 00:23 UTC, pavlovcik approved these changes

2021-09-05 01:44 UTC, pavlovcik commented
I broke this @Zequez currently trying to figure out how to merge :(

2021-09-05 02:19 UTC, pavlovcik commented on frontend/components/common.tsx
> +const PROD = true; //  process.env.NODE_ENV == "production";
Whoops, this is nice for seeing the video in the background in dev though!

2021-09-05 02:19 UTC, pavlovcik commented on tsconfig.json
> +{
Moved this up one because my vscode was not picking up its rules in my text editor/

2021-09-05 02:20 UTC, merged