update github-sript to v6.3.3
ubiquity/ubiquity-dollar pull request #336
Opened 2022-11-18 23:35 UTC by kfukue

Hi,
I was looking into this issue and it seems like the old version of github-script (3.1.0) was causing the warning message:
"Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"
The version is a major upgrade so I'm not sure if there are other consequences so please rollback the changes if the workflow fails.

Thanks,
Keita

Resolves #312

https://github.com/ubiquity/ubiquity-dollar/issues/312

2022-11-20 09:53 UTC, 0xcodercrane requested changes
Thanks for your first contirbution @kfukue . your changes still don't resolve the warning.

2022-11-20 18:49 UTC, kfukue commented
@0xcodercrane Thanks for your reply! Were you referring to this run when you checked if the change didn't resolve the warning? 
https://github.com/ubiquity/ubiquity-dollar/actions/runs/3501048862/jobs/5864294129

2022-11-21 03:59 UTC, 0xcodercrane commented
![image](https://user-images.githubusercontent.com/108444211/202962664-6cb11b9e-acc3-4755-9d4d-cad677508432.png)

Yes, I am. You can look at the warnings in summary menu.

2022-11-21 04:24 UTC, kfukue commented
@0xcodercrane I'm not sure if that run included my change since my change is in the actual workflow file... You can see in my screenshot below and the version of github-script is still @3.1.0 (instead of v6.3.3) . I actually replicated this on my personal repository and I saw the warning disappear when I upgraded to the latest version so I'm hoping this will fix this issue.

I'm not sure if there's a different way to this test this (unless you merge this and create a rollback PR just in case) so please let me know what you think!

![image](https://user-images.githubusercontent.com/4957479/202964692-802455f2-e1bd-4a44-90fd-39b8c3fcd73c.png)

2022-11-21 14:17 UTC, 0xcodercrane commented
Ok let me merge this and make another pr if it doesn't solve the problem

2022-11-21 14:17 UTC, merged

2022-11-21 15:14 UTC, 0xcodercrane commented
it caught up another error once I merge it @kfukue .