Opensea royalty enforcement
ubiquity/ubiquity-dollar pull request #352
Opened 2022-11-30 09:39 UTC by mul1sh

Resolves #315 

- [x] Integrate opensea-filter-registry into UbiquiStick.sol

- [ ] Deploy new UbiquiStick on goerli network

- [ ] Setup royalty fee and address & make sure if royalty works properly.

2022-11-30 10:51 UTC, mul1sh commented
@pavlovcik @0xcodercrane  This is ready for review.

A few things to note,
- The contract has been [deployed to goerli](https://goerli.etherscan.io/address/0xe127e571b46f4de359136b89753965edb26c6d98#code) as required.
- In my opinion the 3rd task `Setup royalty fee and address & make sure if royalty works properly.` is not necessary because the way the **Opensea registry enforces fees** is by banning contracts known to bypass the royalty fees a collection owner sets in Opensea i.e. the contracts specified [here](https://github.com/ProjectOpenSea/operator-filter-registry#filtered-addresses)
- So I have added a test function called `updateOperator` in `UbiquiStick.sol` where you can test this ban functionality.
- To test with this function, pass in any address you have  as `address operator` and `bool filtered` should be `true` if you want the enforcement to be done by the opensea contract and `false` is you don't want any royalty enforcement.
- If `true` you will not be able to  `approve` or `transfer` an NFT after mint from the contract using the banned address
- If false the you will be able to  `approve` or `transfer` an NFT after mint from the contract using the approved address
- Final the `updateOperator` function is only for testing purposes and I will remove it before the final merge to `development`

2022-12-01 02:34 UTC, 0xcodercrane requested changes
Would you please create test file for UbiquiStick.sol including `updateOperator` function you created. It looks like `updateOperator` reverted on goerli network. so we recommend you to give us a proof in forge test. Others look good

2022-12-01 02:34 UTC, 0xcodercrane commented on packages/contracts/src/ubiquistick/UbiquiStick.sol
> +    }
ok. I got your idea. please make sure it gets removed once we merge it.

2022-12-05 12:50 UTC, mul1sh commented
@0xcodercrane thanks for the feedback, added the tests as required. 

Also the Etherscan call failed because the Etherscan input fields don't support input of  `booleans` because they always get formatted as strings/bytes. Anyway I've removed the test function because it's not necessary now with the forge tests.

2022-12-05 13:52 UTC, cuddle-dev requested changes
Lets add tests for other functions you created

2022-12-05 13:52 UTC, cuddle-dev commented on packages/contracts/test/ubiquistick/UbiquiStick.t.sol
> +        vm.expectRevert();
we don't have a revert string here?

2022-12-06 17:56 UTC, mul1sh commented
> Lets add tests for other functions you created

Done 🙂

2022-12-06 21:01 UTC, pavlovcik commented
@mul1sh a new rule we just added a couple days ago is no more force pushing. It makes the review process slower because we can't just compare the previous time we reviewed compared to the current moment review (we have to review all the changes since the beginning of the PR basically.)

Also strangely it appears that CI didn't run on your latest commit. Perhaps this is an effect of force pushing? Does your latest commit pass?

<img width="722" alt="Screenshot 2022-12-07 at 04 59 43" src="https://user-images.githubusercontent.com/4975670/206021746-ddd755ee-b68b-4548-bd1d-b2583b2f0e34.png">

2022-12-06 21:08 UTC, pavlovcik approved these changes
Nothing stands out to me as an issue, but I'm also not a Solidity dev.

2022-12-07 03:24 UTC, 0xcodercrane requested changes
Most stuff looks good to me. Lets just add missing checks and wrap up soon.

2022-12-07 03:24 UTC, 0xcodercrane commented on packages/contracts/test/ubiquistick/UbiquiStick.t.sol
> +        ust.safeTransferFrom(mintTo, transferTo, 1, new bytes(0));
same as above

2022-12-07 03:24 UTC, 0xcodercrane commented on packages/contracts/test/ubiquistick/UbiquiStick.t.sol
> +        ust.transferFrom(mintTo, transferTo, 1);
Lets add a check for the result of transfer like this `assertEq(afterBalance - beforeBalance, 1)` and transfer event as well

2022-12-07 03:24 UTC, 0xcodercrane commented on packages/contracts/test/ubiquistick/UbiquiStick.t.sol
> +        ust.safeTransferFrom(mintTo, transferTo, 1);
same as above

2022-12-09 07:43 UTC, pavlovcik commented
Looks like @0xcodercrane just wants a couple of extra checks added. Everything looks good to me. Looks like you're very close to completing the bounty! Thanks @mul1sh !

2022-12-09 11:14 UTC, mul1sh commented
> Looks like @0xcodercrane just wants a couple of extra checks added. Everything looks good to me. Looks like you're very close to completing the bounty! Thanks @mul1sh !

@pavlovcik @0xcodercrane Done 🙂

2022-12-12 03:15 UTC, 0xcodercrane approved these changes

2022-12-12 03:15 UTC, 0xcodercrane commented
Looks good!

2022-12-12 03:15 UTC, merged