Update NFT case to camelcase
ubiquity/ubiquity-dollar pull request #540
Opened 2023-02-05 13:20 UTC by Steveantor

Updating from [refactor/general-cleanup](https://github.com/ubiquity/ubiquity-dollar/tree/refactor/general-cleanup)
Resolves #

2023-02-06 19:11 UTC, pavlovcik requested changes
I think lets get this merged in as soon as possible before merge conflicts inevitably arise.

2023-02-06 19:11 UTC, 0x4007 commented on packages/contracts/test/helpers/LocalTestHelper.sol
> +        // deploy credit Nft token
```suggestion
        // deploy Credit NFT token
```

2023-02-06 19:11 UTC, 0x4007 commented on packages/contracts/test/dollar/core/CreditNftRedemptionCalculator.t.sol
> +// SPDX-License-Identifier: MIT
Where did this file come from?

2023-02-06 19:11 UTC, 0x4007 commented on packages/contracts/src/dollar/interfaces/ICreditNftRedemptionCalculator.sol
> +/// @title A mechanism for calculating Credit Nfts received for a dollar amount burnt
```suggestion
/// @title A mechanism for calculating Credit NFTs received for a dollar amount burnt
```

2023-02-06 19:11 UTC, 0x4007 commented on packages/contracts/src/dollar/interfaces/ICreditNftManager.sol
> +// SPDX-License-Identifier: MIT
Where did this new file come from?

2023-02-06 19:11 UTC, 0x4007 commented on packages/contracts/src/dollar/core/CreditNft.sol
> +    /// @param expiryBlockNumber the expiration block number of the CreditNfts to burn
```suggestion
    /// @param expiryBlockNumber the expiration block number of the CreditNFTs to burn
```

2023-02-06 19:11 UTC, 0x4007 commented on packages/contracts/src/dollar/core/CreditNft.sol
> +    /// @param creditNftOwner the owner of those CreditNfts
```suggestion
    /// @param creditNftOwner the owner of those CreditNFTs
```

2023-02-06 19:11 UTC, 0x4007 commented on packages/contracts/src/dollar/core/CreditNft.sol
> +    /// @param expiryBlockNumber the expiration block number of the CreditNfts to mint
```suggestion
    /// @param expiryBlockNumber the expiration block number of the CreditNFTs to mint
```

2023-02-06 19:11 UTC, pavlovcik commented
Make sure to rebase onto `development` now that we have CI stable (minus Slither lol)

2023-02-06 21:17 UTC, pavlovcik commented on packages/contracts/src/dollar/interfaces/ICreditNftManager.sol
> +/// @title A Credit Nft redemption mechanism for Credit Nft holders
```suggestion
/// @title A Credit NFT redemption mechanism for Credit NFT holders
```

2023-02-06 21:17 UTC, pavlovcik commented on packages/contracts/src/dollar/interfaces/ICreditNftManager.sol
> +/// @notice Allows users to redeem individual Credit Nft or batch redeem Credit Nft
```suggestion
/// @notice Allows users to redeem individual Credit NFT or batch redeem Credit NFT
```

2023-02-07 10:01 UTC, Steveantor commented on packages/contracts/test/dollar/core/CreditNftRedemptionCalculator.t.sol
> +// SPDX-License-Identifier: MIT
They're not new so what I did was
Delete those files on commit 1,
Restore and rename files on commit 2
Thus avoiding the `gitignorecase ` issue.

2023-02-07 10:01 UTC, Steveantor commented on packages/contracts/src/dollar/interfaces/ICreditNftManager.sol
> +// SPDX-License-Identifier: MIT
They're not new so what I did was
Delete those files on commit 1,
Restore and rename files on commit 2
Thus avoiding the `gitignorecase` issue.

2023-02-07 10:02 UTC, merged