feat: smt checker updates
ubiquity/ubiquity-dollar pull request #634
Opened 2023-05-11 20:42 UTC by FibrinLab

Resolves #578

2023-05-12 06:48 UTC, FibrinLab commented
What has been done so far.

1. Create a separate script like "yarn run build:smt" which only runs smt check. 
2. Foundry.toml modified via a js script to add profile.default.model_checker option.
3. Github workflow created that runs smt check only onworkflow_dispatch (not on every PR, because build time is increased greatly).

Thanks
@pavlovcik @rndquu

2023-05-12 07:57 UTC, rndquu requested changes
@FibrinLab 

Thank you for the PR.

Questions:
1. There are no `targets` set in this PR like here https://github.com/ubiquity/ubiquity-dollar/pull/604/files#diff-5084a3d2809ef6c86199f46d1d985964c92c3a98247da067d6cb04b18b0a40a9R30 . How is it working without the targets?
2. Did you run the script? How long did it take to finish a full SMT check?

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +    name: Build & Test
Pls use more appropriate name

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      contents: read
You sure we need this permission for smt workflow?

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      - name: Setup Node
Unnecessary step

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      - name: Install dependencies
Unnecessary step

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      - name: Yarn Install
Pls leave only the steps required to run SMT checker

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      - name: Set Environment Variables
Unnecessary step

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      - name: Test All
Unnecessary step

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      - name: Prepare Deployment Artifact
Unnecessary step

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      - name: Run Server
Unnecessary step

2023-05-12 07:57 UTC, rndquu commented on .github/workflows/smt-checker.yml
> +      - name: Setup Forge
Probably an unnecessary step

2023-05-12 07:57 UTC, rndquu commented on packages/contracts/scripts/prebuild/smtchecker_prebuild.ts
> +    const namesMatched = contractContent.match(/contract\s+(\w+)\s+(is|{)/g);
Perhaps it is better to use glob as @zgorizzo69 stated here https://github.com/ubiquity/ubiquity-dollar/pull/604#discussion_r1138332187 ? Searching in file content is brittle

2023-05-12 09:15 UTC, pavlovcik commented on .github/workflows/smt-checker.yml
> +          node-version: "18.14.1"
```suggestion
```

2023-05-12 09:16 UTC, pavlovcik commented on .github/workflows/smt-checker.yml
It doesn't look like you incorporated @rndquu's input. You should work on removing the unnecessary steps.

2023-05-12 09:18 UTC, pavlovcik commented on packages/contracts/package.json
> +    "build:smt": "tsx ./scripts/prebuild/smtchecker_prebuild.ts && forge build",
You should use use `npm-run-all` in order to stay consistent with how we do it in this same package.json for the other scripts. e.g. `run-s build:smt build`

Also use kebab case for the file names. So `smtchecker-prebuild.ts` for example.

2023-05-12 09:18 UTC, pavlovcik commented on packages/contracts/scripts/prebuild/smtchecker_prebuild.ts
> +  const fileContent = fs.readFileSync(foundry_file, "utf8");
```suggestion
  const fileContent = fs.readFileSync(foundryFile, "utf8");
```

2023-05-12 09:20 UTC, pavlovcik requested changes
It doesn't look like you incorporated @rndquu's input. You should work on removing the unnecessary steps in the CI. Also I included some code style feedback. Camel casing variables and kebab casing filenames!

2023-05-19 06:37 UTC, pavlovcik reviewed
It seems like there were a lot of unnecessary refactors. Aside from that, it doesn't appear that you resolved @rndquu's comment.

2023-05-19 06:37 UTC, pavlovcik commented on packages/contracts/foundry.toml
> -timeout = 10_000
Why the change?

2023-05-19 06:37 UTC, pavlovcik commented on packages/contracts/scripts/prebuild/smtchecker_prebuild.ts
> +  files.forEach((file) => {
Also curious about this change why its necessary.

2023-05-19 06:37 UTC, pavlovcik commented on packages/contracts/scripts/prebuild/smtchecker_prebuild.ts
> +  /// Problem is from here
What is the problem?

2023-05-19 06:39 UTC, FibrinLab commented
> It seems like there were a lot of unnecessary refactors. Aside from that, it doesn't appear that you resolved @rndquu's comment.

I had to keep some steps so the CI runs. I am making a final commit

2023-06-03 13:04 UTC, sergfeldman commented
As I see, @FibrinLab had not completed this bounty on time and was unassigned https://github.com/ubiquity/ubiquity-dollar/issues/578

@pavlovcik @rndquu Should we close this PR then?

2023-06-04 11:36 UTC, pavlovcik commented
I think that makes sense to close the pull requests when unassigned. Perhaps we should also have the bot do that.

2023-06-04 11:36 UTC, closed without merging