chore: rename `uBOND to `stakingShare`
ubiquity/ubiquity-dollar pull request #638
Opened 2023-05-17 17:29 UTC by eugenioclrc

Resolves #495

2023-05-17 17:40 UTC, pavlovcik approved these changes

2023-05-17 17:41 UTC, pavlovcik reviewed
CI/CD must pass before we can fully review!

2023-05-17 19:37 UTC, eugenioclrc commented
> CI/CD must pass before we can fully review!
Ackwnoledge!

2023-05-17 19:58 UTC, pavlovcik requested changes
Needs to pass CI/CD before we can review.

2023-05-18 08:06 UTC, pavlovcik approved these changes

2023-05-18 08:06 UTC, merged