Refactor erc20 ubiquity
ubiquity/ubiquity-dollar pull request #649
Opened 2023-05-19 14:42 UTC by eugenioclrc

Resolves #644

2023-05-25 21:05 UTC, rndquu requested changes
@eugenioclrc 

Thank you for this PR, pls check the comments 

Not regarded to this PR, also thank you for opening other relevant issues:
- https://github.com/ubiquity/ubiquity-dollar/issues/647
- https://github.com/ubiquity/ubiquity-dollar/issues/646
- https://github.com/ubiquity/ubiquity-dollar/issues/643
- https://github.com/ubiquity/ubiquity-dollar/issues/639

You should have assigned those issues to yourself or simply should have opened PRs, we could discuss bounty prices later. Most of those issues have ready to copy/paste patches so there are guys who took the opportunity to self assign those issues which is ok in terms of how a market works but not really a pleasant UX for issue creator.

Also check this [comment](https://github.com/ubiquity/ubiquity-dollar/issues/639#issuecomment-1554194502) regarding the slither task, perhaps you could be interested in fixing slither errors and revive a slither CI action

2023-05-25 21:05 UTC, rndquu commented on packages/contracts/src/dollar/core/ERC20Ubiquity.sol
> +import {ERC20, ERC20Permit} from "@openzeppelin/contracts/token/ERC20/extensions/draft-ERC20Permit.sol";
Why not `@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol` instead of the draft contract ?

2023-05-25 21:05 UTC, rndquu commented on packages/contracts/src/dollar/core/ERC20Ubiquity.sol
> -    function setSymbol(string memory newSymbol) external onlyAdmin {
`symbol` is not part of the EIP712 so could you get it back because we want to preserve the ability to change the symbol name

2023-05-25 21:05 UTC, rndquu commented on packages/contracts/src/dollar/core/ERC20Ubiquity.sol
> -    function burnFrom(
Why was this method refactored to `function burnFrom(address account, uint256 amount) public virtual;` ?

2023-05-25 21:05 UTC, rndquu commented on packages/contracts/test/diamond/ERC20UbiquityDollarTest.t.sol
> +    address erc20_owner;
All variables in the [ERC20UbiquityDollarTest.t.sol](https://github.com/ubiquity/ubiquity-dollar/blob/71cf980879cf907ab1accc0c3f47a7002c8e0294/packages/contracts/test/diamond/ERC20UbiquityDollarTest.t.sol) are camel cased so could you refactor from snake case to camel case?

2023-05-26 02:54 UTC, pavlovcik commented
> Most of those issues have ready to copy/paste patches so there are guys who took the opportunity to self assign those issues which is ok in terms of how a market works but not really a pleasant UX for issue creator (or first time contributor in your case).

The next release of the bot is to offer direct compensation for issue creators so in the future this problem should be mitigated.

2023-05-26 03:27 UTC, eugenioclrc commented on packages/contracts/src/dollar/core/ERC20Ubiquity.sol
> +import {ERC20, ERC20Permit} from "@openzeppelin/contracts/token/ERC20/extensions/draft-ERC20Permit.sol";
If you check the draft it should be a import of the `ERC20Permit`:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/draft-ERC20Permit.sol

Also, the existance of `...extensions/ERC20Permit.sol` depends to the oz version lib, thats why i publish this issue:
https://github.com/ubiquity/ubiquity-dollar/issues/643

2023-05-26 03:32 UTC, eugenioclrc commented on packages/contracts/src/dollar/core/ERC20Ubiquity.sol
> -    function burnFrom(
All the contracts that extends this one and reimplement the `burnFrom` this mean that the code of this function is never used and should be marked as `virtual`

2023-05-26 03:40 UTC, eugenioclrc commented on packages/contracts/test/diamond/ERC20UbiquityDollarTest.t.sol
> +    address erc20_owner;
https://github.com/ubiquity/ubiquity-dollar/pull/649/commits/99c3f4ee33064804621ee1f69bf2df04a1fdd1a3

2023-05-26 04:13 UTC, eugenioclrc commented on packages/contracts/src/dollar/core/ERC20Ubiquity.sol
> -    function setSymbol(string memory newSymbol) external onlyAdmin {
https://github.com/ubiquity/ubiquity-dollar/pull/649/commits/7075f0fe74c4d96390c4434b6eb70dc642a2ee83

2023-05-26 07:18 UTC, rndquu approved these changes

2023-05-26 14:29 UTC, merged