Refactored Ubiquity Unit Test to fork mainnet
ubiquity/ubiquity-dollar pull request #680
Opened 2023-06-15 07:16 UTC by molecula451

Resolves #

This PR Resolves #630, but i still think theres room for updates unless state otherwise and the team want to close the issue

#### This PR refactors some of the test and purges "Mocks" dependencies on em, but not all, removing the mocks folder it's a not a trivial thing as there are many other testing depending on it, likewise we use ABI compatible on mainnet, we decide to use interfaces within the unit test, because organizing the interfaces within the folders clash! with current mock tests and other tests

#### This PR *Does not* removes or clean Diamonds, diamonds are still being deployed even when forked
![diamond](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/7de43bb7-ea59-460a-8916-9b29fa60d9c8)

#### This PR adds some new custom test like

###### Playing with mainnet 
![new](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/159d6e57-5159-4844-be04-3ca3a62a5a0c)

#### There is an virtual function added on top of *DiamondTestSetup.sol" for bool checking if mainnet is forked 
![override](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/c56ab4ef-3692-49bd-b9d5-777a42ec03d3)

#### Finally refactored some tests that are playing with mainnet returning mainnet values
![pending](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/467c4d2a-162d-49d4-b5ea-40d6cd0846ce)
![pending1](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/6f7eb937-fbc9-4846-8347-acb3a190004d)

2023-06-15 09:28 UTC, rndquu reviewed
The thing is that I don't understand the initial [issue](https://github.com/ubiquity/ubiquity-dollar/issues/630). Yes, we should have tests in a forked environment but in my opinion we should separate unit tests (in a none-forked environment) and integrations tests (in a forked environment).

Besides we don't have a production deploy (with the diamond setup) so there is basically nothing to fork. We can basically fork only the UbiquityDollar contract and users' balances.

@molecula451 did his best trying to fix this issue as he understands it

There are minor issues in this PR like using [deprecated abbreviations](https://github.com/ubiquity/ubiquity-dollar/issues/630), [deprecated interfaces](https://github.com/ubiquity/ubiquity-dollar/pull/680/files#diff-aa687b08fc6d6a877feb71980ee002b4684b3b556ed3d9bfc9b4586b2ccd8748R15) or [modified tests](https://github.com/ubiquity/ubiquity-dollar/pull/680/files#diff-692d683764922b0e75e150bce23518983761153e8b2949bc0bee8083b547cf75R111) although the implementation is untouched. 

The main issue with this PR is that it tries to use **old/deprecated** interfaces with a new diamond setup thus making tests even more complicated to understand.

I would:
1. Close this PR as not planned and use it for future reference for integration testing
2. Mark issue as completed
3. Create separate issues for integration testing in a forked environment

@zgorizzo69 what do you think?

2023-06-15 09:59 UTC, molecula451 commented
> The thing is that I don't understand the initial [issue](https://github.com/ubiquity/ubiquity-dollar/issues/630). Yes, we should have tests in a forked environment but in my opinion we should separate unit tests (in a none-forked environment) and integrations tests (in a forked environment).

that was why I initially asked for brainstorming when started with this one, but to me, it was a good way to get started into the project

> Besides we don't have a production deploy (with the diamond setup) so there is basically nothing to fork. We can basically fork only the UbiquityDollar contract and users' balances.

 Which in turns made no necessary to remove any diamonds testing 

> There are minor issues in this PR like using [deprecated abbreviations](https://github.com/ubiquity/ubiquity-dollar/issues/630), [deprecated interfaces](https://github.com/ubiquity/ubiquity-dollar/pull/680/files#diff-aa687b08fc6d6a877feb71980ee002b4684b3b556ed3d9bfc9b4586b2ccd8748R15) or [modified tests](https://github.com/ubiquity/ubiquity-dollar/pull/680/files#diff-692d683764922b0e75e150bce23518983761153e8b2949bc0bee8083b547cf75R111) although the implementation is untouched.

`

> The main issue with this PR is that it tries to use **old/deprecated** interfaces with a new diamond setup thus making tests even more complicated to understand.

A reminder that not using ABI compatible on mainnet will get us testing `REVERT`

> I would:

> 1. Close this PR as not planned and use it for future reference for integration testing
> 2. Mark issue as completed
> 3. Create separate issues for integration testing in a forked environment

I'd be happy to take the 3 if you guys going to open new issues for alike tasks

2023-06-15 19:59 UTC, pavlovcik commented
Seems like a solid first contribution. Let me ask @zgorizzo69 on telegram and see what they think about this pull request.

2023-06-15 22:04 UTC, pavlovcik commented
The provided video looks good to me https://github.com/ubiquity/ubiquity-dollar/issues/630#issuecomment-1593771178

2023-06-15 22:10 UTC, zgorizzo69 requested changes
I am aligned with @rndquu 
and I think we should close the pr 
we could think about a better way to fork env for integration testing and after that indeed create separate integration tests

2023-06-15 22:10 UTC, zgorizzo69 commented on packages/contracts/test/diamond/facets/StakingFacet.t.sol
> +interface IManagerMainnet {
not a fan of adding interfaces in a test file like this

2023-06-15 22:10 UTC, zgorizzo69 commented on packages/contracts/test/diamond/facets/StakingFacet.t.sol
> +    IERC20 curve3CrvToken = IERC20(0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490);
this are mainnet ETH but what about if we deploy to polygon for instance ? 
A good testing tool would be to have like a generic test setup that you can specialize with addresses from the live network (like adding curve pool address on different mainnet)

2023-06-15 22:10 UTC, zgorizzo69 commented on packages/contracts/test/diamond/facets/ManagerFacet.t.sol
> -            deal(address(IDollar), mintings[i], 10000e18);
for test purposes we don't need to impersonate a whale using deal is fine

2023-06-15 22:14 UTC, molecula451 commented on packages/contracts/test/diamond/facets/StakingFacet.t.sol
> +interface IManagerMainnet {
not adding interfaces like this, would clash with other mock up tests that need other interfaces that are not part of mainnet

2023-06-15 22:15 UTC, molecula451 commented on packages/contracts/test/diamond/facets/StakingFacet.t.sol
> +    IERC20 curve3CrvToken = IERC20(0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490);
I think that would be a certain entry for a new issue as the first one doesn't mention multi-chain anywhere, so the scope a bit different

2023-06-15 22:16 UTC, molecula451 commented on packages/contracts/test/diamond/facets/ManagerFacet.t.sol
> -            deal(address(IDollar), mintings[i], 10000e18);
impersonating works good when doing forked tests and a much better approach, i think so, but yes

2023-06-15 22:38 UTC, molecula451 commented on packages/contracts/test/diamond/facets/ManagerFacet.t.sol
> -            deal(address(IDollar), mintings[i], 10000e18);
this impersonation, creates a pool, add liquidity, transfer to accounts, all within mainnet context & pops outstanding traces

https://www.dropbox.com/s/4mzqgusq27dzsml/metapool.mp4?dl=0

2023-06-15 23:02 UTC, molecula451 commented
gentlemen it looks like we are 2/2, because by the looks says @pavlovcik is +1 & as much as the same way I worked on the tasked, want the PR to make it, as i know theres value, but maybe @rndquu is 50/50, who owns the last word? @zgorizzo69

2023-06-16 06:21 UTC, pavlovcik commented
Unfortunately zgorizzo69 is the code owner of this repository and they said

> and I think we should close the pr

Does it make sense to roll in this work as part of the newly created issue #682? 

Unfortunately I don't quite understand all of these details as I am not a Solidity developer.

2023-06-16 06:29 UTC, molecula451 commented
> Unfortunately zgorizzo69 is the code owner of this repository and they said
> 
> > and I think we should close the pr
> 
> Does it make sense to roll in this work as part of the newly created issue #682?
> 
> Unfortunately I don't quite understand all of these details as I am not a Solidity developer.

this newly opened need more brainstorming as there are points need to be taken, like production deployment mentioned by ndquu, also i notice the label < than a day there, it's not something accomplishable for less than a day

I think this PR mets the requirements for the #630 even tho there may need updates and changes, what about the task there?

2023-06-16 06:30 UTC, pavlovcik commented
> this newly opened need more brainstorming as there are points need to be taken, like production deployment mentioned by ndquu, also i notice the label < than a day there, it's not something accomplishable for less than a day

I think this PR mets the requirements for the https://github.com/ubiquity/ubiquity-dollar/issues/630 even tho there may need updates and changes, what about the task there?

@rndquu I'll let you make the decisions here. Feel free to edit the specifications/merge bounties if needed.

2023-06-16 06:32 UTC, molecula451 commented
> > this newly opened need more brainstorming as there are points need to be taken, like production deployment mentioned by ndquu, also i notice the label < than a day there, it's not something accomplishable for less than a day
> 
> > I think this PR mets the requirements for the #630 even tho there may need updates and changes, what about the task there?
> 
> @rndquu I'll let you make the decisions here. Feel free to edit the specifications/merge bounties if needed.

appreciate so we can start brainstorming the new requirement, I think i can render a layout for the insfrastructure for commenting and feedback

2023-06-16 06:53 UTC, molecula451 commented
basically I handcrafted this one without enough context on what what's coming, but following the requirements as state. and now this PR provides the context for future value.

Otherwise,

This PR plays in mainnet and there are refactored tests that were not initially playing in mainnet, this PR handle specific ABI to be able to catch mainnet data that otherwise would not be possible without adding it, after all this PR actually pass the tests without interfering with other tests that are not mainnet

2023-06-16 16:34 UTC, rndquu commented
To sum up

Initially it is our fault because:
1. Issue description is not clear
2. Even if the description had been clear the PR would have added unnecessary complexity (which basically happened)

At the same time the PR requires additional work even if we considered it for merging

Let's:
1. Close this PR without merging
2. Cut bounty reward in half because the work has been done but we can't accept the PR in its current state

@molecula451 Thank you for your contribution, hope you will continue solving other bounties and understand this middle ground decision.

2023-06-16 17:26 UTC, closed without merging