test: update yarn packages, prettier
ubiquity/ubiquity-dollar pull request #685
Opened 2023-06-18 15:55 UTC by molecula451

Resolves #516 

This PR pass conventional commits, and upgrades & locks requested yarn packages on the issue, this PR does not override prettier config for any of other files than initially was sice it's not clarified, request changes accordingly

2023-06-18 15:58 UTC, pavlovcik commented
Not sure if "latest" is valid and you didn't finish implementing the spec. Lastly, unfortunately the rules are that we allow for 7 days of inactivity before allowing another bounty hunter to submit their solution. As we have more developers in the DevPool we may consider shortening this time period.

2023-06-18 16:00 UTC, molecula451 commented
> Not sure if "latest" is valid and you didn't finish implementing the spec.

I update to latest as the originally posted on the issue, you may request the changes

```
 "devDependencies": {
    "cspell": "latest",
    "prettier": "latest",
    "prettier-plugin-solidity": "latest"
  }
```

https://github.com/ubiquity/ubiquity-dollar/issues/516

Yes, I agree, it's just looked like the issue was not moving forward, just let me know!

>Lastly, unfortunately the rules are that we allow for 7 days of inactivity before allowing another bounty hunter to submit their solution. As we have more developers in the DevPool we may consider shortening this time period.

2023-06-18 16:20 UTC, pavlovcik commented
> Yes, I agree, it's just looked like the issue was not moving forward, just let me know!

I appreciate your eagerness to close issues out. Tag me in a couple of days and I can credit you if the active assignee neglects to finish.

2023-06-19 14:21 UTC, molecula451 commented
> Not sure if "latest" is valid and you didn't finish implementing the spec. Lastly, unfortunately the rules are that we allow for 7 days of inactivity before allowing another bounty hunter to submit their solution. As we have more developers in the DevPool we may consider shortening this time period.

yes "latest" it's a valid for npm/yarn packages

2023-06-19 15:47 UTC, pavlovcik reviewed
This seems correct so far

2023-06-19 16:00 UTC, pavlovcik commented
You need to rename the "prettier" script to "format" in the `package.json` and address the bit about `.prettierrc` comment in the specification. @rndquu do you think you can make sure the spec is followed with @molecula451's implementation

2023-06-19 16:15 UTC, molecula451 commented
provide more context for the `.prettierrc` file @rndquu input would be great

2023-06-19 16:18 UTC, 0x4007 commented
> provide more context for the `.prettierrc` file @rndquu input would be great

> 2 - update the overrides section of the .prettierrc in the root folder

2023-06-19 21:47 UTC, molecula451 commented
> > provide more context for the `.prettierrc` file @rndquu input would be great
> 
> > 2 - update the overrides section of the .prettierrc in the root folder

`.prettierrc` may handle different styles according to a taste, can you guys agree on one? so I shall commit it

2023-06-20 13:22 UTC, rndquu commented
We use prettier as a solidity linter. Lint-staged also calls prettier on commit.

The original [issue](https://github.com/ubiquity/ubiquity-dollar/issues/516) describes a moment in time when we used `forge fmt` as a linter but we moved to prettier so this [issue](https://github.com/ubiquity/ubiquity-dollar/issues/516) should have been closed as "not planned".

Regarding this PR: we shouldn't use `latest` because it introduces dependencies updated with **major versions** which may contain breaking changes. 

So this PR basically brings us:
1. script rename `prettier:all => format:all`
2. some foundry config [optimisations](https://github.com/ubiquity/ubiquity-dollar/pull/685/files#diff-5084a3d2809ef6c86199f46d1d985964c92c3a98247da067d6cb04b18b0a40a9L18)

We can either close this issue as "not planned" either merge this PR (but remove the `latest` versions in `package.json`).

2023-06-20 14:09 UTC, molecula451 commented
> 

Why not planned? you guys agree on a prettier style and we'll do it

2023-06-20 14:12 UTC, rndquu commented
> > 
> 
> Why not planned? you guys agree on a prettier style and we'll do it

I don't see any issues with the current prettier setup for solidity

2023-06-20 14:13 UTC, molecula451 commented
> > > 
> > 
> > 
> > Why not planned? you guys agree on a prettier style and we'll do it
> 
> I don't see any issues with the current prettier setup for solidity

same to, @pavlovcik you may leave the current prettier config, you may propose a change later, this PR is done

2023-06-20 14:39 UTC, rndquu commented
> > > > 
> > > 
> > > 
> > > Why not planned? you guys agree on a prettier style and we'll do it
> > 
> > 
> > I don't see any issues with the current prettier setup for solidity
> 
> i don't either, @pavlovcik you may leave the current prettier config, you may propose a change later, this PR is done
> 
> Yeah, updating the packages as rndquu request

pls also update this [one](https://github.com/ubiquity/ubiquity-dollar/pull/685/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R18)

2023-06-20 14:42 UTC, molecula451 commented
> > > > > 
> > > > 
> > > > 
> > > > Why not planned? you guys agree on a prettier style and we'll do it
> > > 
> > > 
> > > I don't see any issues with the current prettier setup for solidity
> > 
> > 
> > i don't either, @pavlovcik you may leave the current prettier config, you may propose a change later, this PR is done
> > Yeah, updating the packages as rndquu request
> 
> pls also update this [one](https://github.com/ubiquity/ubiquity-dollar/pull/685/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R18)

bumped https://github.com/ubiquity/ubiquity-dollar/pull/685/commits/2aff1a80da17624f87e8325cc9b5b9ce2c560678

2023-06-20 14:53 UTC, rndquu approved these changes

2023-06-21 06:23 UTC, molecula451 commented
let's finish this one

2023-06-21 15:06 UTC, rndquu commented
@molecula451 could you resolve code conflicts?

2023-06-21 15:50 UTC, molecula451 commented
> @molecula451 could you resolve code conflicts?

ther you go, https://github.com/ubiquity/ubiquity-dollar/pull/685/commits/c7f3bcdbf718622810fae2478662731abf1ed522

please merge to avoid code conflicts on the branch

2023-06-21 15:55 UTC, molecula451 commented
@rndquu i just re-synced your PR into the branch

2023-06-21 16:04 UTC, rndquu requested changes

2023-06-21 16:04 UTC, rndquu commented on package.json
>      "clean:all": "yarn workspaces foreach run clean && rimraf node_modules",
`clean:all` and `purge:all` are equal, pls leave only the `clean:all` command

2023-06-21 16:12 UTC, molecula451 commented on package.json
>      "clean:all": "yarn workspaces foreach run clean && rimraf node_modules",
updated here https://github.com/ubiquity/ubiquity-dollar/pull/685/commits/aca85372e08e7124b8627a8810f794104ee699e2

2023-06-21 16:19 UTC, rndquu approved these changes

2023-06-22 04:42 UTC, pavlovcik commented
> i don't either, @pavlovcik you may leave the current prettier config, you may propose a change later, this PR is done

We use `prettier` for everything, including for the UI code under `packages/dapp/` and other codebases. Prettier can also format the Solidity code so the Forge formatter is not necessary.

2023-06-22 04:42 UTC, pavlovcik approved these changes

2023-06-22 04:43 UTC, merged