Fixes cspell not running for everyone consistently
ubiquity/ubiquity-dollar pull request #717
Opened 2023-07-03 10:44 UTC by me505

Resolves #562
This pr is made to resolve cspell not running for everyone consistently by adding it to the build and test ci

2023-07-03 16:46 UTC, me505 commented
@pavlovcik can you review this?

2023-07-04 15:24 UTC, rndquu commented
I don't really understand what issue this PR solves

So we had the [Spell Check workflow](https://github.com/ubiquity/ubiquity-dollar/blob/ed176304f4f89b57ec8975e7bf051261dc6a439f/.github/workflows/spell-check.yml) and now it is run inside the [Build & Test workflow](https://github.com/ubiquity/ubiquity-dollar/pull/717/files#diff-bc668a2c9f2299cef15b222055b4b4d5311646caec2e7610e540cee18ae9b948R72)

So technically nothing has changed

There is also an error on the "Spell Check" [step](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5443658761/jobs/9900465509):
```
199/199 ./utils/kebabalize-typescript-imports.ts 7.46ms
CSpell: Files checked: 199, Issues found: 0 in 0 files
yes: standard output: Broken pipe
```

Besides in the original [issue description](https://github.com/ubiquity/ubiquity-dollar/issues/562#issue-1579772724) @pavlovcik says that the cspell check should be added to the build and test CI while later in the [comments](https://github.com/ubiquity/ubiquity-dollar/issues/562#issuecomment-1502131928) they say that `this bounty is for it to be handled within the husky pre-commit hook`. So again it is not clear how the issue should be resolved.

2023-07-04 16:50 UTC, pavlovcik requested changes

2023-07-04 16:50 UTC, pavlovcik commented on .github/workflows/build-and-test.yml
> +    runs-on: ubuntu-latest
Revert this. We don't want a dynamic environment or else our CI can randomly crash and it'll add complexity to debug.

2023-07-04 16:50 UTC, pavlovcik commented on .github/workflows/build-and-test.yml
> +
`spell-check.yml` should run all the time anyways so I don't see the purpose of you consolidating it inside of `build-and-test.yml`

2023-07-04 16:51 UTC, pavlovcik commented
> I don't really understand what issue this PR solves

Agreed I think this PR is unnecessary.

2023-07-04 17:00 UTC, rndquu commented
> > I don't really understand what issue this PR solves
> 
> Agreed I think this PR is unnecessary.

Should we close the [issue](https://github.com/ubiquity/ubiquity-dollar/issues/562) as not planned or update the description to smth like "make sure husky pre-commit hook runs all the time" ?

2023-07-05 12:48 UTC, closed without merging

2023-07-05 14:12 UTC, pavlovcik commented
Yes it looks like that was my mistake for not updating the spec from the comment below. I have included that comment into the spec.