feat: create tsx for cow zap transaction
ubiquity/ubiquity-dollar pull request #734
Opened 2023-07-17 16:53 UTC by hashedMae

Resolves #610

2023-07-18 23:26 UTC, hashedMae commented
Working on the tests. It's a super simple contract for facilitating the zap. Just need to get the Ubiquity Pool setup to do it.

2023-07-27 18:41 UTC, pavlovcik requested changes

2023-07-27 18:41 UTC, pavlovcik commented on packages/dapp/components/ubiquity-pool/cow-zap.jsx
We only use `.tsx` so this should be renamed and turned into a TypeScript file.

2023-07-27 18:42 UTC, pavlovcik commented
> Just need to get the Ubiquity Pool setup to do it.

Can you elaborate on what you mean by this?

2023-07-27 20:31 UTC, hashedMae commented on packages/dapp/components/ubiquity-pool/cow-zap.jsx
Can do

2023-07-27 20:33 UTC, hashedMae commented
> > Just need to get the Ubiquity Pool setup to do it.
> 
> Can you elaborate on what you mean by this?

The contracts are what is called by CoW Protocol to interact with the UbiquityPoolFacet contract. The setup from the previous tests worked so it really didn't take much.

2023-07-31 17:41 UTC, molecula451 commented
i am drafting this PR as it looks it needs more work to be done, @hashedMae request review when you really think you accomplish the task

2023-08-11 16:13 UTC, molecula451 commented
@rndquu there might be some progress here! but I think this PR doesn't solve the issue #610

- Should we close?
- Should we give an opportunity to the worker with new thoughts, etc? and no dismiss the progress

I think we should close in favor of some thoughts from the hunter

2023-08-11 17:21 UTC, rndquu commented
> @rndquu there might be some progress here! but I think this PR, in it's actual stage doesn't solve the issue #610
> 
> 1. Should we close?
> 2. Should we give an opportunity to the worker with new thoughts, etc? and no dismiss the progress
> 
> I think we should close in favor of some thoughts from the hunter (means give some time to the hunter to provide some thoughts)

I don't understand why you set this PR as ready for review from the draft state

> I think we should close in favor of some thoughts from the hunter

It's actually handled automatically by the bot so let the bot does his job

2023-08-12 23:00 UTC, pavlovcik commented
> It's actually handled automatically by the bot so let the bot does his job

It's supposed to but it missed this one due to the pagination issue. It unassigned mae two weeks ago. I'll close for it being stale.

2023-08-12 23:00 UTC, closed without merging