Fix: Renamed CreditNft and accessControl and added checks to cspell
ubiquity/ubiquity-dollar pull request #742
Opened 2023-07-30 19:05 UTC by Wholesomebruh

Resolves #736

2023-07-31 17:46 UTC, molecula451 commented on packages/dapp/components/utils/local-data.ts
>          console.log((await CreditNFTManager.connect(signer).getCreditNFTReturnedForDollars(signer.getAddress())).toBigInt(), "Credit NFT Returned Dollars");
CreditNft??

2023-08-01 08:54 UTC, rndquu commented
@Wholesomebruh cspell workflow is [failing](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5707906390/job/15465046760?pr=742), could you fix it?

2023-08-01 12:30 UTC, baibhavKumar1 commented
@rndquu , renamed creditNFT to creditNft. All checks are passing.

2023-08-02 15:10 UTC, rndquu requested changes
There still instances of `creditNFT*` in the code

- https://github.com/Wholesomebruh/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibCreditNftManager.sol#L54 (`creditNFTLengthBlocks => creditNftLengthBlocks`)
- https://github.com/Wholesomebruh/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/CreditNftManagerFacet.sol#L24 (`setExpiredCreditNFTConversionRate => setExpiredCreditNftConversionRate`)
- etc...

To sum up all solidity files should be searched for `*CreditNFT*` or `*creditNFT*` and refactored to `*CreditNft*` or `*creditNft*`

Pls refactor

2023-08-02 19:21 UTC, Wholesomebruh commented
@rndquu , is there anything more to change other than all the creditNFT and CreditNFT to creditNft and CreditNft respectively in the "solidity" files or is it required in "ts, js, jsx, tsx" files too? I will be searching for any word that has "credit" or "Credit" with "NFT", and change the NFT to Nft. Please state if there is anything else to add. Thank You.

2023-08-02 19:44 UTC, rndquu commented
> @rndquu , is there anything more to change other than all the creditNFT and CreditNFT to creditNft and CreditNft respectively in the "solidity" files or is it required in "ts, js, jsx, tsx" files too? I will be searching for any word that has "credit" or "Credit" with "NFT", and change the NFT to Nft. Please state if there is anything else to add. Thank You.

Pls refactor only `.sol` files

2023-08-02 21:01 UTC, Wholesomebruh commented
Sorry, just making changes to .sol results in build error. Need to recheck every changes. Close this PR.

2023-08-02 21:01 UTC, closed without merging