feat: UI reinvindication: update UI hook to reuse
ubiquity/ubiquity-dollar pull request #763
Opened 2023-08-16 07:52 UTC by molecula451

Resolves #

2023-08-16 07:53 UTC, molecula451 commented on packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx
> +    if (deployedContracts && provider && provider.network.chainId === NETWORK_ANVIL_ID) {
added to ignore call reverts

2023-08-16 08:45 UTC, molecula451 commented
@rndquu it'll be helpful to me that you add some line comments (on the files) (if possible) of some thoughts as the will help with further UI updates in regard to contract connectivity etc

said, because, i guess sushi pair isn't a thing right now

https://github.com/ubiquity/ubiquity-dollar/blob/be3784f8698702b9ecb2496a6ba0a9d099c883c4/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx#L82

2023-08-16 08:49 UTC, molecula451 commented on packages/dapp/pages/index.tsx
> +        console.log(managedContracts?.dollarToken.address, "MANAGED DOLLAR");
hook in work

2023-08-16 08:50 UTC, molecula451 commented on packages/dapp/pages/index.tsx
> +        console.log(managedContracts);
& hook fetching ALL the addresses at return

https://github.com/ubiquity/ubiquity-dollar/blob/c28cae99bd525b45fbcc7da9539966ca79c8f2b5/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx#L82

2023-08-16 19:48 UTC, molecula451 commented on packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx
> +  const governanceMarket = getUniswapV2PairContract(ZERO_ADDRESS, provider);
@rndquu need some input on this one

2023-08-16 19:57 UTC, molecula451 commented
@rndquu if you run yarn start:anvil && yarn deploy:development

https://173b50b8.ubiquity-dollar-5vd.pages.dev/

this commit will ask you to change the provider to hardhat automatically on  (MetaMask)

check the console and the hook should be fetching the addresses

2023-08-16 21:29 UTC, molecula451 commented on packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx
> +    if (deployedContracts && provider && provider.network.chainId === NETWORK_ANVIL_ID) {
![call](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/1afc82ab-c04d-4728-80c4-9063b6975070)

2023-08-17 00:01 UTC, molecula451 commented
https://github.com/ubiquity/ubiquity-dollar/pull/763/commits/85e8bc4895fe25e4f0359c7f43cfd53e6b35036b update `use-deployed-address.tsx` to enhace reading, it works but it looks unmanageable, this is a much better version for upcoming UI updates

2023-08-17 00:36 UTC, molecula451 commented
i think the `web3 provider` update may be in along with the #528

2023-08-17 06:10 UTC, molecula451 commented on packages/dapp/components/lib/hooks/use-web-3.tsx
> +        chains: defaultChains.slice(),
This does it! 

![commit](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/22359ae8-0a9a-454f-a18e-2691944f98d1)

You getting null on mainnet
You getting the contracts on hardhat (anvil)

2023-08-17 06:14 UTC, molecula451 commented on packages/dapp/components/lib/hooks/use-web-3.tsx
> +        chains: defaultChains.slice(),
instad of showing unsupported network for anvil

2023-08-17 06:16 UTC, molecula451 commented
yarn start:anvil
yarn deploy:development

https://a7632410.ubiquity-dollar-5vd.pages.dev/

Connect as usual and switch to anvil connection

2023-08-17 12:40 UTC, rndquu requested changes
1. This [hook](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) was a mess before the current PR. It still remains a mess. I expected it to be refactored similar to:
```js
// get diamond with all of the facets
const diamondAddress = getLatestDeployedDiamond();
const diamondContract = new ethers.Contract(diamondAddress, DIAMOND_ABI, provider);
// get contracts deployed apart from the diamond (i.e. not part of the diamon's facets)
const dollarContract = new ethers.Contract(dollarAddress, DOLLAR_ABI, provider);
const creditContract = new ethers.Contract(creditAddress, CREDIT_ABI, provider);

return {
  // diamond facets
  accessControl: new ethers.Contract(diamondAddress, ACCESS_CONTROL_ABI, provider),
  collectableDustContract: new ethers.Contract(diamondAddress, COLLECTABLE_DUST_ABI, provider),
  ...other facets
  // separately deployed contracts
  dollarContract,
  creditContract,
  ...other separately deployed contracts
};
```

This way bounty hunters would see the overall project structure (diamond + separate contracts) and it would be easier for them to fix UI.
2. This [hook](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) does not return all of the [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets)
3. Contract naming mismatch ([example](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx#L99): should be [stakingFormulas](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/StakingFormulasFacet.sol))

2023-08-17 13:13 UTC, 0x4007 commented on packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx
> +  const governanceMarket = getUniswapV2PairContract(ZERO_ADDRESS, provider);
`governanceMarket` is supposed to be the SushiSwap `uAD-UBQ` market but I think we should migrate to Uniswap. Why is this reset to `0x0`? The market currently exists.

2023-08-17 13:18 UTC, molecula451 commented
> Member




> 1. This [hook](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) was a mess before the current PR. It still remains a mess. I expected it to be refactored similar to:
> 
> ```js
> // get diamond with all of the facets
> const diamondAddress = getLatestDeployedDiamond();
> const diamondContract = new ethers.Contract(diamondAddress, DIAMOND_ABI, provider);
> // get contracts deployed apart from the diamond (i.e. not part of the diamon's facets)
> const dollarContract = new ethers.Contract(dollarAddress, DOLLAR_ABI, provider);
> const creditContract = new ethers.Contract(creditAddress, CREDIT_ABI, provider);
> 
> return {
>   // diamond facets
>   accessControl: new ethers.Contract(diamondAddress, ACCESS_CONTROL_ABI, provider),
>   collectableDustContract: new ethers.Contract(diamondAddress, COLLECTABLE_DUST_ABI, provider),
>   ...other facets
>   // separately deployed contracts
>   dollarContract,
>   creditContract,
>   ...other separately deployed contracts
> };
> ```
> 
> This way bounty hunters would see the overall project structure (diamond + separate contracts) and it would be easier for them to fix UI. 2. This [hook](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) does not return all of the [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets) 3. Contract naming mismatch ([example](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx#L99): should be [stakingFormulas](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/StakingFormulasFacet.sol))

If we do `new.ethers.Contract`

```js
return {
  // diamond facets
  accessControl: new ethers.Contract(diamondAddress, ACCESS_CONTROL_ABI, provider),
  collectableDustContract: new ethers.Contract(diamondAddress, COLLECTABLE_DUST_ABI, provider),
  ...other facets
  // separately deployed contracts
  dollarContract,
  creditContract,
  ...other separately deployed contracts
};
```

We would not be relying on this [contract component](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/utils/contracts.ts) that is in charge of take abi etc.. maybe something similar according to your suggestion?

2023-08-17 13:24 UTC, molecula451 commented on packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx
> +  const governanceMarket = getUniswapV2PairContract(ZERO_ADDRESS, provider);
this was until clarification, not really resseting to a zero address, more input is welcoming

2023-08-17 13:31 UTC, pavlovcik commented
> We would not be relying on this [contract component](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/utils/contracts.ts) that is in charge of take abi etc.. maybe something similar according to your suggestion?

Type cast it?

```js
// get diamond with all of the facets
const diamondAddress = getLatestDeployedDiamond();
const diamondContract = new ethers.Contract(diamondAddress, DIAMOND_ABI, provider) as DiamondContract;
// get contracts deployed apart from the diamond (i.e. not part of the diamon's facets)
const dollarContract = new ethers.Contract(dollarAddress, DOLLAR_ABI, provider) as DollarToken;
const creditContract = new ethers.Contract(creditAddress, CREDIT_ABI, provider) as CreditToken;

```

2023-08-17 13:37 UTC, molecula451 commented
> > We would not be relying on this [contract component](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/utils/contracts.ts) that is in charge of take abi etc.. maybe something similar according to your suggestion?
> 
> Type cast it? Perhaps I'm not understanding the issue.
> 
> ```ts
> // get diamond with all of the facets
> const diamondAddress = getLatestDeployedDiamond();
> const diamondContract = new ethers.Contract(diamondAddress, DIAMOND_ABI, provider) as DiamondContract;
> // get contracts deployed apart from the diamond (i.e. not part of the diamon's facets)
> const dollarContract = new ethers.Contract(dollarAddress, DOLLAR_ABI, provider) as DollarToken;
> const creditContract = new ethers.Contract(creditAddress, CREDIT_ABI, provider) as CreditToken;
> ```


I think it's cleaner to keep to the fetch by the shorthand function component, i'm wondering since rndquu suggestion shows `new.ethers.Contract`

2023-08-17 13:39 UTC, molecula451 commented
> > We would not be relying on this [contract component](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/utils/contracts.ts) that is in charge of take abi etc.. maybe something similar according to your suggestion?
> 
> Type cast it? Perhaps I'm not understanding the issue.
> 
> ```ts
> // get diamond with all of the facets
> const diamondAddress = getLatestDeployedDiamond();
> const diamondContract = new ethers.Contract(diamondAddress, DIAMOND_ABI, provider) as DiamondContract;
> // get contracts deployed apart from the diamond (i.e. not part of the diamon's facets)
> const dollarContract = new ethers.Contract(dollarAddress, DOLLAR_ABI, provider) as DollarToken;
> const creditContract = new ethers.Contract(creditAddress, CREDIT_ABI, provider) as CreditToken;
> ```

no worries @pavlovcik , your input is always welcome and necessary (when possible and even if you dont understand), we make things better that way

2023-08-17 13:46 UTC, rndquu commented
> > Member
> 
> > 1. This [hook](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) was a mess before the current PR. It still remains a mess. I expected it to be refactored similar to:
> > 
> > ```js
> > // get diamond with all of the facets
> > const diamondAddress = getLatestDeployedDiamond();
> > const diamondContract = new ethers.Contract(diamondAddress, DIAMOND_ABI, provider);
> > // get contracts deployed apart from the diamond (i.e. not part of the diamon's facets)
> > const dollarContract = new ethers.Contract(dollarAddress, DOLLAR_ABI, provider);
> > const creditContract = new ethers.Contract(creditAddress, CREDIT_ABI, provider);
> > 
> > return {
> >   // diamond facets
> >   accessControl: new ethers.Contract(diamondAddress, ACCESS_CONTROL_ABI, provider),
> >   collectableDustContract: new ethers.Contract(diamondAddress, COLLECTABLE_DUST_ABI, provider),
> >   ...other facets
> >   // separately deployed contracts
> >   dollarContract,
> >   creditContract,
> >   ...other separately deployed contracts
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way bounty hunters would see the overall project structure (diamond + separate contracts) and it would be easier for them to fix UI. 2. This [hook](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) does not return all of the [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets) 3. Contract naming mismatch ([example](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx#L99): should be [stakingFormulas](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/StakingFormulasFacet.sol))
> 
> If we do `new.ethers.Contract`
> 
> ```js
> return {
>   // diamond facets
>   accessControl: new ethers.Contract(diamondAddress, ACCESS_CONTROL_ABI, provider),
>   collectableDustContract: new ethers.Contract(diamondAddress, COLLECTABLE_DUST_ABI, provider),
>   ...other facets
>   // separately deployed contracts
>   dollarContract,
>   creditContract,
>   ...other separately deployed contracts
> };
> ```
> 
> We would not be relying on this [contract component](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/utils/contracts.ts) that is in charge of take abi etc.. maybe something similar according to your suggestion?

Yes, we could also refactor this [file](https://github.com/ubiquity/ubiquity-dollar/blob/21ffe14e37d9ee626ce8e2fcca8a9f3817bf8a72/packages/dapp/components/utils/contracts.ts) (or create a new one)

The main point is that there should be a single place in the code which returns all of our contracts:
1. Separate contract for each of the diamond's [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets)
2. [Other](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/core) separately deployed contracts (Dollar, Credit, etc...)

2023-08-17 16:01 UTC, molecula451 commented on packages/dapp/components/lib/hooks/use-web-3.tsx
> +        chains: defaultChains.slice(),
this one, it's going to be refactored but not on this PR, on this PR i will leave as it, fetching for all the contracts

the refactor is to make sure it doesn't look for anvil on mainnet network and just for dev or debug variable is activated

2023-08-18 07:52 UTC, molecula451 commented
> The main point is that there should be a single place in the code which returns all of our contracts:

This is the task of the [ManagerFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/ManagerFacet.sol) address! so we basically have to refactor **ManagerFacet** with the other contract facets to bring the rest to the front end

but one thing take a look at this bug!

If we want to bring the [bancorFormulaAddress](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/facets/ManagerFacet.sol#L407) e.g (with the **ManagerFacet** contract in it's actual stage) to the front end

we will get
![front](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/e1350aa4-288b-4e6d-89f4-cff773eb15d5)

[We find out that the address it's not set
](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/Diamond.sol#L53C10-L53C10)

Even tho it was already there from older commits! so I pressume, this will happen with any other new addition to the **ManagerFacet** as pivot to other facets

Which lead to the task to design and **debug**, iterate the contracts, this will take a bit, i wouldn't like to stale this PR nor to keep it drafted while debugging on design, so feel free to update the task description a bit or to not close the issue but commit this PR as there are good changes here,  maybe recheck? while i work on the update for this contracts or as last let me know if we are drafting this a bit while i debug

2023-08-18 08:06 UTC, rndquu commented
> so we basically have to refactor ManagerFacet with the other contract facets to bring the rest to the front end

I don't understand. How exactly we should refactor the `ManagerFacet` contract and why?

> If we want to bring the [bancorFormulaAddress](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/facets/ManagerFacet.sol#L407) (just an example) (with the ManagerFacet contract in it's actual stage) to the front end

Why can't we get it this way?

```
const diamondAddress = "0x01";
const managerContract = new ethers.Contract(diamondAddress, MANAGER_FACET_ABI, provider);
```

> Some of the facets that needs to be pivoted

What do you mean by "pivoted"?

2023-08-18 08:15 UTC, molecula451 commented
> I don't understand. How exactly we should refactor the `ManagerFacet` contract and why?

take a look a the ManagerFacet how it brings the facets that are already available on the hook (and remember this manager itself it's a facet)

> Why can't we get it this way?
> 
> ```
> const diamondAddress = "0x01";
> const managerContract = new ethers.Contract(diamondAddress, MANAGER_FACET_ABI, provider);
> ```

We are doing this. Manager becomes the main diamond to fetch the address
also this hook is spread everywhere on the UI. Deprecating it, it means re-touch the whole UI and clean at all.

We are just re-using and the diamond main address it's fetched [here](https://github.com/molecula451/ubiquity-dollar/blob/3b186b9a936e803c468a784bbe4182019e6cdc62/packages/dapp/components/lib/hooks/contracts/use-deployed-contracts.tsx#L10)

Which is after **yarn deploy:development** **0xbe0efAbc83686a81903C1D4a2515f8111e53B5Cb**

> What do you mean by "pivoted"?

To turn in, to make use of. The types artifacts are not generated within it's supposely to be 
```ts
ManagerFacet.getBondingCurveFacet()
```

this type it's not available anywhere. Bring it alone, it's not what we want

2023-08-18 09:26 UTC, rndquu commented
@molecula451 

This [issue](https://github.com/ubiquity/ubiquity-dollar/issues/731) implies creating a **single file** which returns:
1. All of the contracts that exist as the diamond facets
2. All of the contracts that are not part of the diamond

We don't need to refactor the whole UI in the current issue, neither refactoring solidity contracts. Imagine that the repo is empty and we need the code that fetches all of the project's contracts in the UI.

2023-08-18 17:49 UTC, molecula451 commented
> @molecula451 
> 
> This [issue](https://github.com/ubiquity/ubiquity-dollar/issues/731) implies creating a **single file** which returns:
> 1. All of the contracts that exist as the diamond facets
> 2. All of the contracts that are not part of the diamond
> 
> We don't need to refactor the whole UI in the current issue, neither refactoring solidity contracts. Imagine that the repo is empty and we need the code that fetches all of the project's contracts in the UI.

Creating a file won't make use of this Hook at all. Please take a bit of to digest the last answer while i debug things on my end and lets draw further points

2023-08-18 20:29 UTC, rndquu commented
> The main point is that there should be a single place in the code which returns all of our contracts

> @rndquu This is the task of the [ManagerFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/ManagerFacet.sol) address! so we basically have to refactor ManagerFacet with the other contract facets to bring the rest to the front end

No, this is not the task of the [ManagerFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/ManagerFacet.sol) to return all of the contracts. In the early days there was a contract `UbiquityManager` which was responsible for storing contract addresses. Now we moved to the diamond proxy and `UbiquityManager` became `ManagerFacer` where most of the methods are obsolete because all of them return the same diamond address. For example, this [method](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/facets/ManagerFacet.sol#L113), this [method](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/facets/ManagerFacet.sol#L79), this [method](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/facets/ManagerFacet.sol#L153), all of them are setting the same diamond address right now which doesn't make sense. They should be either refactored, either deleted (which is part of another task).

We shouldn't build the frontend code that returns all of the contracts around the `ManagerFacet` but rather around the `Diamond` and separately deployed contracts (Dollar, Credit, etc...).

2023-08-18 20:51 UTC, molecula451 commented
> > The main point is that there should be a single place in the code which returns all of our contracts
> 
> > @rndquu This is the task of the [ManagerFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/ManagerFacet.sol) address! so we basically have to refactor ManagerFacet with the other contract facets to bring the rest to the front end
> 
> No, this is not the task of the [ManagerFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/ManagerFacet.sol) to return all of the contracts. In the early days there was a contract `UbiquityManager` which was responsible for storing contract addresses. Now we moved to the diamond proxy and `UbiquityManager` became `ManagerFacer` where most of the methods are obsolete because all of them return the same diamond address. For example, this [method](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/facets/ManagerFacet.sol#L113), this [method](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/facets/ManagerFacet.sol#L79), this [method](https://github.com/ubiquity/ubiquity-dollar/blob/7e39594538f29922977806752352ee86246ef895/packages/contracts/src/dollar/facets/ManagerFacet.sol#L153), all of them are setting the same diamond address right now which doesn't make sense. They should be either refactored, either deleted (which is part of another task).
> 
> We shouldn't build the frontend code that returns all of the contracts around the `ManagerFacet` but rather around the `Diamond` and separately deployed contracts (Dollar, Credit, etc...).

Making sense but this should imply deprecating the ManagerFacet hook which is spread across many part of the UI

2023-08-18 21:42 UTC, pavlovcik commented
@rndquu perhaps sketching/rendering visual diagrams could be helpful for complex specifications like what we are starting to see here in `ubiquity-dollar`

2023-08-18 21:46 UTC, molecula451 commented
Yes as a last, i think we are moving this forward in subsequently issues, the thing is the original issue was about the "hook" but if we're deprecating this hook, then we have to revamp many part of the UI to avoid clashing. But in either way, should strive to keep the UI actively on deploys, while activelely refactoring it

2023-08-19 08:22 UTC, rndquu commented
> @rndquu perhaps sketching/rendering visual diagrams could be helpful for complex specifications like what we are starting to see here in `ubiquity-dollar`
> 
> An iPad Pro with Apple Pencil has gotten me through many moments like these.

I will create a new wiki page with the protocol architecture when we have all of the contracts [upgradable](https://github.com/ubiquity/ubiquity-dollar/discussions/730)

2023-08-23 21:16 UTC, rndquu commented
Closing this one in favour of https://github.com/ubiquity/ubiquity-dollar/pull/771

@molecula451 pls feel free to open separate PRs for each bug that the current PR solves

2023-08-23 21:16 UTC, closed without merging

2023-09-27 13:27 UTC, rndquu commented
> > @rndquu perhaps sketching/rendering visual diagrams could be helpful for complex specifications like what we are starting to see here in `ubiquity-dollar`
> > An iPad Pro with Apple Pencil has gotten me through many moments like these.
> 
> I will create a new wiki page with the protocol architecture when we have all of the contracts [upgradable](https://github.com/ubiquity/ubiquity-dollar/discussions/730)

https://github.com/ubiquity/ubiquity-dollar/wiki/23.-Smart-Contracts-Architecture