Anvil Custom Methods
ubiquity/ubiquity-dollar pull request #766
Opened 2023-08-20 11:11 UTC by Keyrxng

Resolves #528

I have added a "Custom RPC Methods" button which expands to show the input area and CTA for the methods.  I have added the methods mentioned but I'm curious whether or not I should just go ahead and add them all, or at least a few others maybe?

As for the data dumping call, should that hash just be written to a local file and pushed with everything else I assume?

Is there a need for some kind of frontend notification that the call was made? Anvil logs show them but nothing on the browser just now.

No testing done yet to confirm everything is working, thought I'd touch in and see if I'm on the right track first.

![Screenshot 2023-08-20 114031](https://github.com/ubiquity/ubiquity-dollar/assets/106303466/31b746b6-4696-4e10-96ea-8b2f65e07734)
![Screenshot 2023-08-20 114109](https://github.com/ubiquity/ubiquity-dollar/assets/106303466/aeee1060-3fd9-4e60-848f-32798993669d)
![Screenshot 2023-08-20 120931](https://github.com/ubiquity/ubiquity-dollar/assets/106303466/fca0aa86-ad68-438f-897a-a4a49e16f2e6)

2023-08-20 11:22 UTC, pavlovcik commented
> curious whether or not I should just go ahead and add them all, or at least a few others maybe?

Your call. Use your best judgement! I didn't research this in a long time, but seems like a good idea to expose more tools to developers.

2023-08-20 11:32 UTC, Keyrxng commented
No problem leave it with me.

I read through discussions about trying to persist the anvil server through a public domain and then talks about using the dataDump to perform the poor man's version of this for various scenarios so I wasn't sure if you had something in mind specifically for it yet.

Yeah I feel the same, it's pretty redundant to have a toast system set up for the messages if anvil is logging everything anyway.

Alright I'll keep on as I am for now then, cheers!

2023-08-20 12:03 UTC, rndquu commented
> I have added the methods mentioned but I'm curious whether or not I should just go ahead and add them all, or at least a few others maybe?

Start with the ones mentioned in the [issue](https://github.com/ubiquity/ubiquity-dollar/issues/528). If you've added more then we appreciate it.

> As for the data dumping call, should that hash just be written to a local file and pushed with everything else I assume?

As far as I understand `anvil_dumpState` returns a string representing the whole blockchain state. Can we simply download it as a file?

> Is there a need for some kind of frontend notification that the call was made?

If anvil logs everything then there is no need to implement frontend notifications in the current issue.

2023-08-20 21:26 UTC, Keyrxng commented
I think that about wraps this up, unless there is anything else.

Any function can be removed by deleting the entry from ```method-configs.ts```. Only Dumps, Anvil info and Snapshots are set for downloading at the moment. I've naively categorized them into three subsets of calls.

I'm going to look into the below points and will do what I can. It was my first and it was fun but I will become a more active contributor after such a good experience with it today. Let me know if there's anything further that needs looked at with this.

anvil_enableTraces makes a call but doesn't appear to do anything bar throw an error along the lines of "Not Implemented".

loggingEnabled also makes a call but doesn't appear to do anything.

MemPool functions require Geth integration.

So how does it work now, do I submit this ready for review or do I wait for correspondence first? For future reference I mean.

2023-08-21 04:38 UTC, pavlovcik commented
If you believe the work is complete according to the specification, then you can convert this into a regular pull request and our review team will take a look as soon as possible. Thanks for your contribution!

2023-08-21 10:46 UTC, rndquu commented
@Keyrxng So this PR is ready for review, right?

2023-08-21 10:47 UTC, Keyrxng commented
Got one more push coming then I'll submit it for review, cheers!

2023-08-21 18:53 UTC, Keyrxng commented
The Build & Test check has failed during yarn install due to Lavamoat here but in my own attempts to have a deployed dapp instance I'm getting errors which are down to outdated deps. 

Has there been a discussion about upgrading from Ethers to Viem? 

Ethers vs Viem [benchmarks](https://viem.sh/docs/benchmarks.html).
Quick-read [article](https://jamesbachini.com/ethers-vs-viem/).

Better performance. Smaller bundle size (~130kb to ~27kb). Rapid widespread adoption.

Wagmi should also be updated for a host of reasons, better-than-previous built-in react hooks as well as Wagmi/CLI integration as part of the build process would generate react hooks for any contract changes with input and output type checked ready to work straight out of the box. 

I suggest this as I've used Viem when building this pr and from the looking around I've done regarding the build error it's more than likely the above is the problem.

Thoughts?

2023-08-21 20:12 UTC, pavlovcik commented
Updating dependencies is fine but we will stick with Ethers because it's industry standard and that makes maintenance simpler. I've never heard of the alternative until now.

2023-08-21 20:28 UTC, rndquu requested changes
@Keyrxng 

1. https://github.com/ubiquity/ubiquity-dollar is a monorepo with 2 packages: [contracts](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts) and [dapp](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/dapp). [This](https://github.com/ubiquity/ubiquity-dollar/pull/766/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R77) `viem` dependency is defined in the `package.json` root so it is assumed to be used by both packages but at the moment it is used only by the `dapp` package. Pls remove `viem` from the root's `package.json` and keep only [this one](https://github.com/ubiquity/ubiquity-dollar/pull/766/files#diff-589a3117ed1a146cce8e29d734a204c6b5df1aa0e3e65fdb66fb4e5eb421f09fR59).
2. "Kebab case" workflow is [failing](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5925933881/job/16066354742?pr=766). To fix it you could add the `hardhat.config.js` file to [exceptions](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5925933881/workflow?pr=766#L17)
3. Pls fix the [build workflow](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5925933876/job/16066354386?pr=766)

Overall I don't understand why `viem` was chosen for RPC node communication while we use `ethers.js` everywhere in the project. Anyway I think we can keep it as a one-off solely for the "anvil cheats" feature.

2023-08-21 22:45 UTC, pavlovcik commented
Why is a hardhat config in here? We made a special effort to remove hardhat as a dependency and only use Foundry. Again, t this is for code maintainability reasons.

2023-08-22 13:09 UTC, Keyrxng commented
Truthfully it was added because I saw that you were still using Hardhat as one of the default chains, so while I added the foundry chain import and commented out the Hardhat one as it clashes with both, I thought I should add the hardhat-foundry plugin thinking you guys were using tasks or something but thanks for clearing that up.

I've removed Viem altogether as it's not required to call they anvil methods. However, if you ever need to upgrade ConnectKit, WalletConnect or Wagmi you'll have to migrate. There is an open issue (unacknowledged) on the UniswapV3Core repo requesting Viem support, I expect long term they'll make the switch too but widgets still uses Ethers so all good.

I'm fixed the check issues, cheers.

2023-08-22 14:18 UTC, pavlovcik commented
> * [ae8ad20](https://880471a2.ubiquity-dollar-5vd.pages.dev)

What is the purpose of this logo? Can you fix or remove? 

![missing-logos](https://github.com/ubiquity/ubiquity-dollar/assets/4975670/e7953a1c-b8ef-4009-ab19-876559b33243)

2023-08-22 14:43 UTC, pavlovcik commented on packages/dapp/package.json
> +    "@nomicfoundation/hardhat-foundry": "^1.0.2",
```suggestion
```

2023-08-22 14:50 UTC, pavlovcik commented
Download button doesn't seem to do anything. Also theres an error in rendering the table

```
client.js:1 Warning: validateDOMNesting(...): <tbody> cannot appear as a child of <div>.
    at tbody
    at div
    at div
    at div
    at div
    at AnvilRpcs (webpack-internal:///./components/layout/anvil/anvil-rpcs.tsx:18:82)
    at div
    at Sidebar
    at div
    at Layout (webpack-internal:///./components/layout/layout.tsx:67:11)
    at BalancesContextProvider (webpack-internal:///./components/lib/hooks/use-balances.tsx:26:11)
    at TransactionsContextProvider (webpack-internal:///./components/lib/hooks/use-transaction-logger.tsx:20:11)
    at Fe (webpack-internal:///../../node_modules/styled-components/dist/styled-components.browser.esm.js:31:17316)
    at ConnectKitProvider (webpack-internal:///../../node_modules/connectkit/build/index.es.js:9153:31)
    at QueryClientProvider (webpack-internal:///../../node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:48:3)
    at WagmiConfig (webpack-internal:///../../node_modules/wagmi/dist/index.js:134:3)
    at UseWeb3Provider (webpack-internal:///./components/lib/hooks/use-web-3.tsx:86:11)
    at CombinedComponents (webpack-internal:///./components/lib/combine-components.tsx:30:15)
    at CombinedComponents (webpack-internal:///./components/lib/combine-components.tsx:14:19)
    at CombinedComponents (webpack-internal:///./components/lib/combine-components.tsx:14:19)
    at CombinedComponents (webpack-internal:///./components/lib/combine-components.tsx:14:19)
    at Ubiquity (webpack-internal:///./pages/_app.tsx:37:11)
    at PathnameContextProviderAdapter (webpack-internal:///../../node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:303:63)
    at ReactDevOverlay (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:852:919)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:62:1)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:172:11)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:347:11)
```

2023-08-22 15:30 UTC, pavlovcik approved these changes

2023-08-22 15:31 UTC, 0x4007 commented
Any luck with the table rendering console error? Its not fatal, but still, shouldn't be there.

2023-08-22 15:34 UTC, pavlovcik commented on packages/dapp/components/layout/anvil/anvil-rpcs.tsx
> -      console.log("error", error);
Perhaps you can fix the error instead of hiding it?

2023-08-22 15:38 UTC, Keyrxng commented on packages/dapp/components/layout/anvil/anvil-rpcs.tsx
> +      /* empty */
replaced with /* empty */ for eslint.

2023-08-22 16:17 UTC, Keyrxng commented on packages/dapp/components/layout/anvil/anvil-rpcs.tsx
> +      /* empty */
fixed the failing methods being incorrectly typed. Any user error will be logged by rpc result.

2023-08-22 16:31 UTC, Keyrxng commented
I misread your comment at first @pavlovcik but methods should be fixed now.

You can also test things with cast but Metamask struggles to stay updated, the balance is reduce to 0 in the wallet but does update on chain.


![image](https://github.com/ubiquity/ubiquity-dollar/assets/106303466/8b354feb-213b-41ae-9cf3-1aad5faefdae)

2023-08-22 22:21 UTC, rndquu commented
@Keyrxng Is `eth_sendTransaction` implemented?

2023-08-23 00:45 UTC, Keyrxng commented
Okay so I have managed to get ```eth_sendTransaction``` working but there's a caveat:

We can only send transactions from either the 10 built-in accounts or one we are have the private key for, we can't sign transactions from impersonated accounts. Sending from one of the built-in accounts automatically signs the transaction under the hood.

We have ```eth_sendRawTransaction``` as well but quite a bit of setup to get this operational I think.

Also, Eth Sign only works when called from the built-in accounts it seems.

2023-08-23 01:09 UTC, Keyrxng commented
There are a few that would need quite a bit more work in order to get set up but could be very beneficial like the set, get & remove block filter functions as well as the get & filter logs.

The three Txpool functions would require a GETH integration so they have been removed for now.

loggingEnabled and enableTraces definitely aren't fully functional so they've been removed for now as well.

As a lot of the optional inputs have been left out (particularly sendTransaction) things could be improved a lot more to allow these to be modified as well, if that was the case it would be good to have a clear list of which functions to expand on specifically (filters, logs etc) perhaps as another issue would be good as the spec here has been achieved I think.

2023-08-23 01:39 UTC, 0x4007 commented
> We have `eth_sendRawTransaction` as well but quite a bit of setup to get this fully operational I think, it's callable and executes but the transaction object would need to be built properly first.

> There are a few that would need quite a bit more work in order to get set up but could be very beneficial like the set, get & remove block filter functions as well as the get & filter logs.

We can make new tasks for these if they are projects, and if you can help us spec it out. @rndquu if you know what is a priority please feel free to make those tasks and get them funded as well.

2023-08-23 22:26 UTC, rndquu approved these changes

2023-08-23 22:27 UTC, rndquu commented
@Keyrxng awesome, thank you

2023-08-23 22:28 UTC, merged

2023-08-23 23:14 UTC, Keyrxng commented
The first of many (¬‿¬)