chore: refactor creditclock as facet
ubiquity/ubiquity-dollar pull request #777
Opened 2023-08-25 19:51 UTC by molecula451

Resolves #

2023-08-25 21:24 UTC, molecula451 commented on packages/contracts/scripts/deploy/dollar/solidityScripting/00_Constants.s.sol
> +    bytes16 constant RATE_START_VALUE = (0x00);
to be update for production values

2023-08-28 14:37 UTC, rndquu requested changes
Facets can't have state variables (at least in our project).

Check this [facet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/CollectableDustFacet.sol). All of the state variables for the `CollectableDustFacet` contract are managed in a separate library [here](https://github.com/ubiquity/ubiquity-dollar/blob/36b920515eebcf4d8db08fc51d36f08e571755b4/packages/contracts/src/dollar/libraries/LibCollectableDust.sol#L29) starting from special [slot](https://github.com/ubiquity/ubiquity-dollar/blob/36b920515eebcf4d8db08fc51d36f08e571755b4/packages/contracts/src/dollar/libraries/LibCollectableDust.sol#L45).

With the current `CreditClockFacet` [implementation](https://github.com/ubiquity/ubiquity-dollar/blob/2519eb41248e485e1c0ccdf054f24b8c1a68982d/packages/contracts/src/dollar/facets/CreditClockFacet.sol), in case we add a new facet with state variables then those state variables (from `CreditClockFacet` and a newly added facet) will start to rewrite each other because all of them would start from slot 0 (and keeping in mind that the `Diamond` contract uses `delegatecall()` to call facets).

Pls refactor `CreditClockFacet` to use a library which accesses all of `CreditClockFacet` state variables starting from a special slot `ubiquity.contracts.credit.clock.storage`.

2023-09-04 07:05 UTC, rndquu commented
@molecula451 Is it ready for review?

2023-09-04 07:26 UTC, molecula451 commented
> @molecula451 Is it ready for review?

I'm finishing things up on `CreditClockFacet.t.sol`

2023-09-18 13:18 UTC, rndquu commented
@molecula451 Any updates? The bot should've [closed](https://github.com/ubiquity/ubiquity-dollar/issues/772#issuecomment-1704749887) this PR 2 weeks ago

2023-09-18 13:30 UTC, molecula451 commented
> @molecula451 Any updates? The bot should've [closed](https://github.com/ubiquity/ubiquity-dollar/issues/772#issuecomment-1704749887) this PR 2 weeks ago

I got this stale, i need to tackle a bug on the access control modifier after the implementation, this could be closed tho, if someone else comes with a PR for the issue, it's also good

2023-09-18 13:37 UTC, molecula451 commented
closing, i will re-open if re-start working on it & if there is no new PR's

2023-09-18 13:37 UTC, closed without merging