feat(ui): apply diamond architecture to the remained or missed components
ubiquity/ubiquity-dollar pull request #824
Opened 2023-10-17 11:37 UTC by bojan07

Resolves #807

2023-10-17 17:07 UTC, bojan07 commented
@rndquu @molecula451 PR is ready for a review. I have debugged updates, and works well in my side.

2023-10-18 17:29 UTC, molecula451 commented
Can You make sure there are no linter warnings those when You build the dapp `yarn build:dapp` and pop

2023-10-18 17:38 UTC, bojan07 commented
> Can You make sure there are no linter warnings those when You build the dapp `yarn build:dapp` and pop

![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/1ddb1ac1-9e10-456b-8502-7df555c9cbff)
Build was successful. A few prettier warnings

2023-10-18 17:42 UTC, molecula451 commented
> > Can You make sure there are no linter warnings those when You build the dapp `yarn build:dapp` and pop
> 
> ![image](https://user-images.githubusercontent.com/121951004/276345482-1ddb1ac1-9e10-456b-8502-7df555c9cbff.png) Build was successful. A few prettier warnings

those are known, you may ignore em, is this PR really ready? you seem to be asking things at #807

2023-10-18 17:45 UTC, bojan07 commented
> > > Can You make sure there are no linter warnings those when You build the dapp `yarn build:dapp` and pop
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/121951004/276345482-1ddb1ac1-9e10-456b-8502-7df555c9cbff.png) Build was successful. A few prettier warnings
> 
> those are known, you may ignore em, is this PR really ready? you seem to be asking things at #807

Yeah, except for `uAR` replacement, all is ready

2023-10-18 17:57 UTC, molecula451 commented
are you testing the changes with the whole connection `yarn start:anvil && yarn deploy:development`

2023-10-18 17:58 UTC, bojan07 commented
> are you testing the changes with the whole connection `yarn start:anvil && yarn deploy:development`

Yeah, I am.

2023-10-19 07:18 UTC, rndquu requested changes
<img width="1512" alt="Screenshot 2023-10-19 at 10 16 31" src="https://github.com/ubiquity/ubiquity-dollar/assets/119500907/6aacd902-ac22-4b3a-bcfc-fef526d0c4da">

The [inventory component](https://github.com/ubiquity/ubiquity-dollar/blob/73e19b308f4f622d6ce28ca0aedddfdd3c37a110/packages/dapp/components/layout/inventory.tsx) is rendered with errors if balances are set. Pls make sure that all of the components are rendered without errors.

2023-10-19 08:17 UTC, bojan07 commented
> The [inventory component](https://github.com/ubiquity/ubiquity-dollar/blob/73e19b308f4f622d6ce28ca0aedddfdd3c37a110/packages/dapp/components/layout/inventory.tsx) is rendered with errors if balances are set. Pls make sure that all of the components are rendered without errors.

How to set balances and check? I'm testing with first wallet on anvil testnet imported in Metamask

2023-10-19 09:37 UTC, rndquu commented
> > The [inventory component](https://github.com/ubiquity/ubiquity-dollar/blob/73e19b308f4f622d6ce28ca0aedddfdd3c37a110/packages/dapp/components/layout/inventory.tsx) is rendered with errors if balances are set. Pls make sure that all of the components are rendered without errors.
> 
> I have already test it by setting the balances manually when debugging. How to set balances and check? I'm testing with first wallet on anvil testnet imported in Metamask

Simply set the balances manually in the code

2023-10-19 09:41 UTC, bojan07 commented
> > > The [inventory component](https://github.com/ubiquity/ubiquity-dollar/blob/73e19b308f4f622d6ce28ca0aedddfdd3c37a110/packages/dapp/components/layout/inventory.tsx) is rendered with errors if balances are set. Pls make sure that all of the components are rendered without errors.
> > 
> > 
> > I have already test it by setting the balances manually when debugging. How to set balances and check? I'm testing with first wallet on anvil testnet imported in Metamask
> 
> Simply set the balances manually in the code

Yeah, how to set BigNumber manually?

2023-10-19 09:43 UTC, bojan07 commented
> > > > The [inventory component](https://github.com/ubiquity/ubiquity-dollar/blob/73e19b308f4f622d6ce28ca0aedddfdd3c37a110/packages/dapp/components/layout/inventory.tsx) is rendered with errors if balances are set. Pls make sure that all of the components are rendered without errors.
> > > 
> > > 
> > > I have already test it by setting the balances manually when debugging. How to set balances and check? I'm testing with first wallet on anvil testnet imported in Metamask
> > 
> > 
> > Simply set the balances manually in the code
> 
> Yeah, how to set BigNumber manually?

resolved, `Bignumber.from()` works

2023-10-19 10:33 UTC, bojan07 commented
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/7df92d3d-81b0-4a38-ad34-dd8b8cd8c8a4)
Fixed inventory error

2023-10-20 07:22 UTC, rndquu requested changes
There is an error in the inventory component on render, pls fix:
<img width="1512" alt="Screenshot 2023-10-20 at 10 16 33" src="https://github.com/ubiquity/ubiquity-dollar/assets/119500907/7c124e16-bd99-4b07-94f0-cbb685e61918">

Pls also provide QA with screenshots of all of the rendered components mentioned in the [original issue](https://github.com/ubiquity/ubiquity-dollar/issues/807).

2023-10-20 08:58 UTC, bojan07 commented
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/16d10f7a-5de3-4473-80b4-8d796d32ac52)

2023-10-20 09:34 UTC, bojan07 commented
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/5c279be6-4be6-46d5-af8b-3442f4d2b293)
This error is just normal error that is generated because there is no pair in curve meta pool, as I know

2023-10-20 09:48 UTC, bojan07 commented
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/ec3b822d-ffdd-48c3-addc-c95d40039e40)
DAI-USDT returns the value, but DOLLAR-USDC returns error.

2023-10-20 10:00 UTC, bojan07 commented
> There is an error in the inventory component on render, pls fix: <img alt="Screenshot 2023-10-20 at 10 16 33" width="1512" src="https://user-images.githubusercontent.com/119500907/276852225-7c124e16-bd99-4b07-94f0-cbb685e61918.png">
> 
When testing after running anvil testnet and deploying contracts, this kind of error will not happen. I can't find this kind of error in my side

2023-10-20 10:12 UTC, bojan07 commented
Just removed the possibility of that error case in [this commit](https://github.com/ubiquity/ubiquity-dollar/pull/824/commits/070fa7206312994fb517807b6b1064b83a799ec2)

2023-10-20 10:19 UTC, bojan07 commented
> ![image](https://user-images.githubusercontent.com/121951004/276892343-ec3b822d-ffdd-48c3-addc-c95d40039e40.png) DAI-USDT returns the value, but DOLLAR-USDC returns error.

If new pairs were made with newly deployed Dollar token in the curve pool, this kind of errors will be disappeared

2023-10-20 10:24 UTC, bojan07 commented
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/9a943714-be86-4334-a311-a7cf2f24de06)

2023-10-20 10:27 UTC, molecula451 commented
> This error is just normal error that is generated because there is no pair in curve meta pool, as I know

there is a pair

2023-10-20 10:28 UTC, molecula451 commented
there is a pair, you can mock a Pair to test the components too

2023-10-20 10:37 UTC, bojan07 commented
Can I know the already deployed uAD address?

2023-10-20 10:48 UTC, bojan07 commented
> Can I know the already deployed uAD address?

Found that address
https://etherscan.io/address/0x0f644658510c95cb46955e55d7ba9dda9e9fbec6
Passed `get_coin_indices` function, but now new error - `INVALID TOKEN` related to twap oracle
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/086ccdb4-37d2-418a-80e4-0b0085a52fe4)

2023-10-20 10:55 UTC, molecula451 commented
> > Can I know the already deployed uAD address?
> 
> Found that address https://etherscan.io/address/0x0f644658510c95cb46955e55d7ba9dda9e9fbec6 Passed `get_coin_indices` function, but now new error - `INVALID TOKEN` related to twap oracle ![image](https://user-images.githubusercontent.com/121951004/276907332-086ccdb4-37d2-418a-80e4-0b0085a52fe4.png)

test with diamond uAD

2023-10-20 11:00 UTC, bojan07 commented
> `INVALID TOKEN` related to twap oracle

Had a look at `TWAPOracleDollar3poolFacet` contract. Because I have tested  with old dollar address in stead of newly deployed dollar address, it doesn't exist on `twap oracle storage`.. so invalid token..
How can I mock the pair?

2023-10-20 11:04 UTC, molecula451 commented
> > `INVALID TOKEN` related to twap oracle
> 
> Had a look at `TWAPOracleDollar3poolFacet` contract. Because I have tested with old dollar address in stead of newly deployed dollar address, it doesn't exist on `twap oracle storage`.. so invalid token.. How can I mock the pair?

the tests have this interactions, theres mocking pairs etc here https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/test try to achieve something similar to test the components

2023-10-20 11:04 UTC, molecula451 commented
> > > `INVALID TOKEN` related to twap oracle
> > 
> > 
> > Had a look at `TWAPOracleDollar3poolFacet` contract. Because I have tested with old dollar address in stead of newly deployed dollar address, it doesn't exist on `twap oracle storage`.. so invalid token.. How can I mock the pair?
> 
> the tests have these interactions, theres mocking pairs etc here https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/test try to achieve something similar to test the components

2023-10-20 11:11 UTC, bojan07 commented
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/157e72ef-4fac-44bc-8761-bb3c750fa65b)
Just tested, working well

2023-10-20 11:14 UTC, molecula451 commented
> ![image](https://user-images.githubusercontent.com/121951004/276912978-157e72ef-4fac-44bc-8761-bb3c750fa65b.png) Just tested by setting the return value of consult function of `twap oracle` manually, working well

nice please show us some console.log beautiness

2023-10-20 11:15 UTC, molecula451 commented
>  Just tested by setting the return value of consult function of `twap oracle` manually, working well

but i still think this is not what we really want, try to achieve the result without manually setting

2023-10-20 11:42 UTC, bojan07 commented
> nice please show us some console.log beautiness

![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/8d5c891a-db8b-4e60-b032-8721c26f7490)

2023-10-20 11:45 UTC, bojan07 commented
> > Just tested by setting the return value of consult function of `twap oracle` manually, working well
> 
> but i still think this is not what we really want, try to achieve the result without manually setting

Then, We should update deployment script(when running yarn deploy:development) to create pairs in curve meta pool.. not quite needed in this QA testing stage

2023-10-20 11:56 UTC, molecula451 commented
please test the components mock a pair you dont need to change deployment script in this PR what you need to do is test the components which whatever way possible

2023-10-20 11:58 UTC, bojan07 commented
> please test the components mock a pair you dont need to change deployment script in this PR what you need to do is test the components which whatever way possible

Yeah, mocking pair involves solidity works, not ui works?

2023-10-20 12:16 UTC, bojan07 commented
@molecula451 I'm quite new to ubiquity-dollar project and only solved ui related 3 issues. So, involving solidity works might require much time for me.. I think mocking Pair is not a MUST for QA of the PR.. so hope to skip mocking pair

2023-10-20 16:10 UTC, rndquu commented
@bojan07 pls provide QA screenshots for the following components:
- https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/layout/inventory.tsx
- https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/debt-coupon-deposit.tsx
- https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/ucr-nft-redeem.tsx
- https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/ucr-redeem.tsx

2023-10-20 16:56 UTC, bojan07 commented
> @bojan07 pls provide QA screenshots for the following components:
> 
> * https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/layout/inventory.tsx
> * https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/debt-coupon-deposit.tsx
> * https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/ucr-nft-redeem.tsx
> * https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/ucr-redeem.tsx

inventory component is imported in each page, so homepage screenshot shows it
And other 3 components are imported in staking page
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/db57529a-a5b9-4574-9b95-34438fa8289c)

2023-10-20 17:25 UTC, bojan07 commented
https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/debt-coupon.tsx
This component also has been updated regarding to name convention. and it shows in `credit-nft` page
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/154c2a41-d24f-43af-a3e0-168cd6970467)

2023-10-21 11:01 UTC, rndquu commented
@bojan07 

> inventory component is imported in each page, so homepage screenshot shows it

Yes, it is imported in each page but there are no any screenshots where it is rendered with balances, pls provide one.

2023-10-21 11:47 UTC, bojan07 commented
> @bojan07
> 
> > inventory component is imported in each page, so homepage screenshot shows it
> 
> Yes, it is imported in each page but there are no any screenshots where it is rendered with balances, pls provide one.

![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/d0ba8bd1-0a3d-42d2-956b-3f2e1f03d585)

2023-10-21 11:54 UTC, bojan07 commented
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/b1f0ecb5-2ff2-45ec-96e3-284f421d4f3d)

2023-10-21 13:19 UTC, bojan07 commented
Fixed broken ui
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/9dd35e54-1c0a-4e20-beb0-5e247fe7c588)

2023-10-23 06:39 UTC, rndquu requested changes
@bojan07 Overall look fine, pls fix some naming issues

2023-10-23 06:39 UTC, rndquu commented on packages/dapp/components/utils/contracts.ts
> +import _INftsForDollarsCalculator from "@ubiquity/contracts/out/ICreditNftRedemptionCalculator.sol/ICreditNftRedemptionCalculator.json";
```suggestion
import _ICreditNftRedemptionCalculator from "@ubiquity/contracts/out/ICreditNftRedemptionCalculator.sol/ICreditNftRedemptionCalculator.json";
```

2023-10-23 06:39 UTC, rndquu commented on packages/dapp/components/utils/contracts.ts
> +import _ICreditForDollarsCalculator from "@ubiquity/contracts/out/ICreditRedemptionCalculator.sol/ICreditRedemptionCalculator.json";
```suggestion
import _ICreditRedemptionCalculator from "@ubiquity/contracts/out/ICreditRedemptionCalculator.sol/ICreditRedemptionCalculator.json";
```

2023-10-23 06:39 UTC, rndquu commented on packages/dapp/components/utils/contracts.ts
> +export const getINftsForDollarsCalculatorContract = (address: string, provider: Provider) => {
```suggestion
export const getCreditNftRedemptionCalculatorContract = (address: string, provider: Provider) => {
```

2023-10-23 06:39 UTC, rndquu commented on packages/dapp/components/utils/contracts.ts
> +export const getICreditForDollarsCalculatorContract = (address: string, provider: Provider) => {
```suggestion
export const getCreditRedemptionCalculatorContract = (address: string, provider: Provider) => {
```

2023-10-23 06:53 UTC, bojan07 commented on packages/dapp/components/utils/contracts.ts
> +export const getICreditForDollarsCalculatorContract = (address: string, provider: Provider) => {
done it

2023-10-23 07:02 UTC, rndquu approved these changes

2023-10-24 05:20 UTC, bojan07 commented
@molecula451 how is the review going? I'm waiting for your review

2023-10-24 09:30 UTC, molecula451 approved these changes
This PR only adds cosmetical diamond changes but importants and needed, there doesn't seem to be major refactoring only the changes and deletes of managed-manager hook (which was planned) necessary for the well-being of the app and furthercoming diamond connections

2023-10-24 09:30 UTC, merged