Improved readme
ubiquity/ubiquity-dollar pull request #843
Opened 2023-11-22 21:17 UTC by molecula451

Resolves #

2023-12-01 16:14 UTC, gitcoindev commented
Hi @molecula451 is this still a draft pull request or can be reviewed?

2023-12-01 16:23 UTC, molecula451 commented
draft but you are welcome to leave suggestions

2023-12-01 17:39 UTC, gitcoindev requested changes

2023-12-01 17:39 UTC, gitcoindev commented on README.md
> +yarn start # starts the user interface and daemonize'd to continue to run tests in the background
Currently this command fails on a clean checkout as the "start" script definition is not available in the top level package.json and is defined in packages/dapp only.

2023-12-01 17:39 UTC, gitcoindev commented on README.md
> +yarn start # starts the user interface and daemonize'd to continue to run tests in the background
Additionally, when we remove `&` the dapp starts in the foreground mode, therefore everything written after "starts the user interface" can be removed. We should explicitly add though that this command runs in foreground and another shell / console must be open for subsequent commands to run in parallel to the user interface.

2023-12-01 17:46 UTC, molecula451 commented on README.md
> +yarn start # starts the user interface and daemonize'd to continue to run tests in the background
as this is a bound to change, yarn start it's available under /dapp, which make it practical to use

2023-12-09 15:20 UTC, rndquu approved these changes

2023-12-09 17:40 UTC, gitcoindev approved these changes

2023-12-09 17:40 UTC, merged