chore: initialize [#1](https://github.com/ubiquity/ubiquity-dollar/is…
ubiquity/ubiquity-dollar pull request #981
Opened 2024-12-17 19:46 UTC by kingsley-einstein

Resolves [#979](https://github.com/ubiquity/ubiquity-dollar/issues/979)

2025-01-02 21:02 UTC, rndquu requested changes
@kingsley-einstein 

1. Pls fix the comments
2. Did you deploy the contracts to the testnet?
3. Did you check that the trap works as expected?
4. The trap must pause the contracts.
5. CI should pass.

2025-01-02 21:02 UTC, rndquu commented on .gitmodules
> +[submodule "packages/contracts/lib/v3-periphery"]
Why do we need this submodule? It's not used anywhere.

2025-01-02 21:02 UTC, rndquu commented on packages/contracts/src/traps/ProtocolTrap.sol
> +contract ProtocolTrap {
Contract must implement `ITrap`.

2025-01-02 21:02 UTC, rndquu commented on packages/contracts/src/traps/ProtocolTrap.sol
> +        uint256 randomNumber = randomize();
What's the point of returning a random number?

2025-01-15 23:06 UTC, kingsley-einstein commented
@rndquu 
The trap contract has been deployed. For it to work, I think an operator has to opt into it. I'm guessing I'll have to opt to become an operator as no operator has opted in since I deployed the contract.

2025-01-16 09:49 UTC, rndquu commented
> @rndquu The trap contract has been deployed. For it to work, I think an operator has to opt into it. I'm guessing I'll have to opt to become an operator as no operator has opted in since I deployed the contract.

Drosera runs its own operators and drosera team made us sure there will be at least 1 operator in our trap. So becoming an operator is unnecessary, it's drosera's job.

2025-01-28 08:58 UTC, closed without merging